### ISSUE TITLE
The injector

### ISSUE THREAD

**Issue by vikster125** [axstin/rbxfpsunlocker#1]
The injector is deleted every time i try to run it

**Comment by axstin** [comment]
This is probably due to your antivirus detecting a false positive. Try temporarily disabling it or better yet, compile the source yourself with Visual Studio.

**Comment by vikster125** [comment]
do i have to disable it for the whole time im using it or just when it starts up?

from Vikram
________________________________

**Comment by vikster125** [comment]
And what is Visual Stidio

from Vikram
________________________________

**Comment by vikster125** [comment]
studio*

from Vikram
________________________________

**Comment by axstin** [comment]
If disabling your antivirus fixes the issue, enable it again and add an exception for injector.exe or the folder it is in (if you don't know how to do this, Google "how to add exception to your_anti_virus antivirus").

**Comment by vikster125** [comment]
thx

from Vikram
________________________________

**Comment by vikster125** [comment]
Hi,

I've just signed the following petition "This Morning : A PETITION TO SAVE
OUR DOG, TANK." and wanted to see if you could help by adding your name.

Our goal is to reach 300,000 signatures and we need more support. You can
read more and sign the petition here:

https://chn.ge/2xdtAsG

Thanks!
Vikram
