### ISSUE TITLE
Fps Unlocker Roblox

### ISSUE THREAD

**Issue by N3RD-Nexus** [axstin/rbxfpsunlocker#100]
My fps isnt increasing its still the same

**Comment by xVortexinator** [comment]
I've noticed the same, as well. I think they need to update their FPS unlocker for ROBLOX. I installed their newest release for the ROBLOX FPS unlocker, executed it, and my FPS still caps out at 60. 

Hopefully they get on releasing/fixing the current issue with it soon.

**Comment by N3RD-Nexus** [comment]
how do i fix this problem?

**Comment by xVortexinator** [comment]
I don't think we can fix it ourselves. I think we have to wait for the creator of the file to update it.

**Comment by xVortexinator** [comment]
Edit: It appears to be working now. I just tried opening the file and executing it again (when in game), and it surpassed 60 FPS. Try it now. If it still doesn't work, it is most likely an issue on your end of the spectrum.

**Comment by N3RD-Nexus** [comment]
ok i will try also im not using my gaming pc im using my laptop which normally gets around 40-60 fps

**Comment by PhoenixShay** [comment]
fps unlocker only removes the 60fps cap, it cannot boost your FPS or improve your computer
