### ISSUE TITLE
FPS Unlock

### ISSUE THREAD

**Issue by xBlizzardz** [axstin/rbxfpsunlocker#101]
Hey. I've been looking everywhere for an FPS Unlocker created for other OS other than Windows. Do you think there is a way to use FPS Unlocker/Framerate Unlock on devices that run macOS? It would be greatly appreciated as in some games it can lead us to a disadvantage.

Your help is greatly appreciated.

**Comment by N3RD-Nexus** [comment]
i think it works also on mac but im not sure tho i will check

**Comment by CelestiusBlitz** [comment]
C# doesn't work natively on MacOS, so it is impossible for this program to run on a Mac. Apologies.

**Comment by N3RD-Nexus** [comment]
u can use wine bottler it changes windows files to mac

**Comment by axstin** [comment]
I currently don't have plans to add Mac support myself (see [FAQ](https://github.com/axstin/rbxfpsunlocker#FAQ)). However, this project is open source and those with experience writing macOS software are free to port the project.
