### ISSUE TITLE
Only works when I click off the client

### ISSUE THREAD

**Issue by Lokenop** [axstin/rbxfpsunlocker#107]
What I mean: when clicking off the client I see the fps cap go back up to my desired setting, but when 
                     clicking to resume playing it goes back to 60

**Comment by mxdanger** [comment]
Are you referring to the console log window or the Roblox client?

**Comment by Lokenop** [comment]
The Roblox client itself

**Comment by axstin** [comment]
Do you know your monitor's refresh rate? This sounds like a Vsync setting/feature imposed by your graphics software (AMD/Nvidia/etc.), by Windows, or even by Roblox causing the FPS to drop when the window is focused.

Do you have Nvidia, AMD, or Intel graphics?
Does the issue occur in fullscreen (try F11 and Alt+Enter)?

Thanks
