### ISSUE TITLE
FPS Not working correctly.

### ISSUE THREAD

**Issue by rinfl** [axstin/rbxfpsunlocker#108]
Firstly I'd like to say my PC is way capable of reaching 60+ FPS.

FPS Locker works within FPS Unlocker however only under 60 FPS (30 FPS Works).

Once FPS Unlocker is ran I can not exceed 60 FPS, I've tried installing FPS Unlocker multiple times hoping it'll fix this issue however it has not.

Any solution on this?

Hope to hear from you soon.
-Rin

**Comment by rinfl** [comment]
Just to add on, I've noticed it's working whenever I go onto my desktop screen.

Whenever I go back into the ROBLOX screen it goes back to 60 FPS.

**Comment by mxdanger** [comment]
What refresh rate is your monitor?

**Comment by rinfl** [comment]
> What refresh rate is your monitor?

60 Hz refresh rate

**Comment by mxdanger** [comment]
Then it is working as intended. Why would you get this if you only have 60hz monitor. The game is already set to 60fps and the vsync is set to your monitor refresh rate.
