### ISSUE TITLE
"Unable to Find TaskScheduler"

### ISSUE THREAD

**Issue by Legend7475** [axstin/rbxfpsunlocker#118]
![error](https://user-images.githubusercontent.com/30220740/68440904-49df4780-0181-11ea-9599-06895c50c019.png)

Just got this issue a couple of days ago, and everytime I open up my FPS Unlocker it just spams this pop-up message. Sometimes my FPS Unlocker works, but it's started to be random once this error popped out of nowhere.

**Comment by axstin** [comment]
How frequent is this?

**Comment by Legend7475** [comment]
I get this pop-up every time the FPS Unlocker minimizes. The pop ups appear right after another one is closed. With this issue, my FPS Unlocker only works in about 1 out of 5 games played.

**Comment by TheUserName2006** [comment]
Is there any solution for this problem?!

**Comment by axstin** [comment]
Is this still a problem in [v4.1.1](https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.1.1)?

If so, if you exit RFU and then open it again after joining a game, do you ever get the popup or is it only when RFU is already running and you join a new game?

A screenshot/paste of RFU's debug console would be helpful as well (RFU->Toggle Console)

Thanks

**Comment by Legend7475** [comment]
No problem in v4.1.1; tysm.
