### ISSUE TITLE
Getting Blocked by my eScan antivirus and blocker

### ISSUE THREAD

**Issue by dave1001232** [axstin/rbxfpsunlocker#119]
its keep on saying Failed-Forbidden Insufficient permissions and when i hop on my eScan the reason is saying Infected by Trojan Virus sorry if there's o pic but this it what it says and i cant whitelist it/View Quarantined Objects but the weird thing is it works on my Core i7 8th gen from DELL : "11/8/2019 13:51:52","C:\Users\User\Downloads\Unconfirmed 572189.crdownload","Infected by Virus: Trojan.GenericKD.32594820 (DB)","File Deleted",183

**Comment by axstin** [comment]
Please see FAQ: https://github.com/axstin/rbxfpsunlocker#FAQ
Add a folder to your Antivirus's exclusions and save the download there
