### ISSUE TITLE
Ping Spikes when using Unlocker

### ISSUE THREAD

**Issue by Uhix** [axstin/rbxfpsunlocker#12]
Basically what the title says, whenever I turn on the fps unlocker my ping spikes up to 1000+. I mean my average ping isn't that good anyway but never has it ever spiked up to 1000 or higher.

**Comment by Pokl1** [comment]
adjust your network settings

roblox studio > file > settings > network

change datamtuadjust to 0
change receiverate to 60

datamtuadjust at 0 allows more remote events/functions without delay
recieverate at 60 receiving data quicker so your client can interpret it quicker, going above 60 is unstable at times and may increase ping, if must change to 59.


other then that you should only get above 1k ping when downloading a lot/big assets in a game, you can always check that with shift + f3

**Comment by PhoenixShay** [comment]
if this issue is still happening, please post a video that starts before joining the game or running fps unlocker
