### ISSUE TITLE
Fps unlocker not working.

### ISSUE THREAD

**Issue by GoldenGabber** [axstin/rbxfpsunlocker#122]
says the variable scan has failed.
![2019-11-13 19_07_19-New Issue · axstin_rbxfpsunlocker](https://user-images.githubusercontent.com/57725426/68791237-2fa5dd80-0649-11ea-8c7e-d3f897fc8fdf.png)

**Comment by axstin** [comment]
https://github.com/axstin/rbxfpsunlocker/issues/126
