### ISSUE TITLE
fpsunlocker not working due to a roblox update

### ISSUE THREAD

**Issue by BillStrachan** [axstin/rbxfpsunlocker#126]
another day on my pc, boot it up, play some jailbreak and phantom forces. there is then a roblox update. so i finish the update join a game  and the fps unlocker gives me a message that says: variable scan failed! this is probably due to a roblox update--watch the github for any patches or a fix. please fix the game is not the same without 160fps

![image](https://user-images.githubusercontent.com/57728707/68799370-0a53a800-0626-11ea-8177-5fa236a6815f.png)

**Comment by axstin** [comment]
Resolved in latest update: https://github.com/axstin/rbxfpsunlocker/releases
