### ISSUE TITLE
Issue setting fps unlocker up.

### ISSUE THREAD

**Issue by Blizzyrdz** [axstin/rbxfpsunlocker#127]
![image](https://user-images.githubusercontent.com/57726490/68802888-b4e3bf00-0656-11ea-8e45-57a5df76d3b5.png)

**Comment by axstin** [comment]
Try extracting the zip file first instead of running rbxfpsunlocker.exe from inside. If you're having issues with your anti-virus, see FAQ: https://github.com/axstin/rbxfpsunlocker#FAQ

**Comment by Blizzyrdz** [comment]
Hello, It did not work because on the 4.1 fps unlocker it download properly but on the 4.1.1 it does not work,.
