### ISSUE TITLE
Launch crash

### ISSUE THREAD

**Issue by Whoisthise2** [axstin/rbxfpsunlocker#129]

**Comment by mxdanger** [comment]
Use the description when posting issues and don’t write your entire problem in the title.

The solution to your problem is to read this: [README.md#faq](https://github.com/axstin/rbxfpsunlocker/blob/master/README.md#faq).

**Comment by Whoisthise2** [comment]
I downloaded the new version and then when i went to extract the file i opened fps unlocker and joined a game as soon as i joined the game, the game crashed and fps unlocker crashed and just disappeared.

**Comment by axstin** [comment]
Moving this issue to: https://github.com/axstin/rbxfpsunlocker/issues/133
