### ISSUE TITLE
Not detecting .dll when opening with explorer

### ISSUE THREAD

**Issue by Pokl1** [axstin/rbxfpsunlocker#13]
Opening from windows explorer without being in the folder will not detect the .dll file

K:\rbxfpsunlocker 2.0\rbxfpsunlocker.exe

**Comment by Pokl1** [comment]
Still not fixed with version 3.0

**Comment by axstin** [comment]
Don't think I can fix this unless I have the unlocker install to some predetermined location (like in Program Files or AppData) so it always knows where the .dll is. I currently don't have plans to do this. Have you thought about using a shortcut and putting it somewhere (start menu, desktop, taskbar, etc.)?
