### ISSUE TITLE
IDP.ARES.GENERIC

### ISSUE THREAD

**Issue by tanticsroblox** [axstin/rbxfpsunlocker#132]
Tried to download and open the new update for fpsunlocker but my antivirus came up with IDP.ARES.GENERIC
wondering why it shows up on here?

**Comment by mxdanger** [comment]
This isn’t a problem, please close this issue and at the very least read the [FAQ](https://github.com/axstin/rbxfpsunlocker/blob/master/README.md#faq) before you make a redundant issue.
