### ISSUE TITLE
Launch Crash

### ISSUE THREAD

**Issue by cookiefy** [axstin/rbxfpsunlocker#133]
when you launch the fps unlocker, it will run for a few seconds and then crash roblox and close itself and then roblox goes back to its cap

**Comment by Whoisthise2** [comment]
Same problem

**Comment by wayatat** [comment]
same

**Comment by axstin** [comment]
Define "crash roblox." How are you able to see that Roblox "goes back to its cap" if it crashed? What does the crash look like?

**Comment by Whoisthise2** [comment]
The game simply just closes as if you just x'd it.

**Comment by wayatat** [comment]
i launch fps unlocker then open roblox game i see its work and after 5 to 20 sec its just crash game closing and fpsunlocker to

**Comment by cookiefy** [comment]
> Define "crash roblox." How are you able to see that Roblox "goes back to its cap" if it crashed? What does the crash look like?

a few seconds in after launching rbxfpsunlocker.exe, It will close out roblox just like any other game you'd close

**Comment by wayatat** [comment]
> > Define "crash roblox." How are you able to see that Roblox "goes back to its cap" if it crashed? What does the crash look like?
> 
> a few seconds in after launching rbxfpsunlocker.exe, It will close out roblox just like any other game you'd close

yes and rbxfpsunlocker.exe too

**Comment by wayatat** [comment]
i can show it to you on disc if u want

**Comment by Whoisthise2** [comment]
yes fix it please

**Comment by axstin** [comment]
If you guys are able to capture the debug console before it crashes that would be a great help (RFU Icon->Toggle Console)

**Comment by Whoisthise2** [comment]
http://prntscr.com/px1bkw
If this is what you meant, but I'm not sure what you mean

**Comment by cookiefy** [comment]
im pretty sure i have fixed this issue, but ill keep it open for others

**Comment by cookiefy** [comment]
nevermind about the issue being fixed, this has a chance of it happening but its not 100% but you have to keep the console app open to actually keep roblox from crashing itself.

**Comment by axstin** [comment]
Do you crash at any cap or only higher ones? Sharing your system specs would be helpful as well (32- or 64-bit OS, Windows version, graphics card, etc.)

**Comment by IamBadatLife** [comment]
lmao i didin't understand any of this...

**Comment by cookiefy** [comment]
im on windows 10, gtx 660, I7 2600K Processor and 24 gigs of ram

**Comment by XxAbdurrahmanxX10** [comment]
same

**Comment by 4ndyBruh** [comment]
Same im on windows 10
