### ISSUE TITLE
It Makes Me Lag

### ISSUE THREAD

**Issue by Shiroshaki** [axstin/rbxfpsunlocker#134]
Idk its not the fps but it made the ping higher, when i try playing without the unlocker its fine but when i use the unlocker the ping sky rocket

**Comment by axstin** [comment]
Can you provide examples of your ping/FPS before and after using the unlocker? Does it affect gameplay?

**Comment by Zewwo-Boi** [comment]
Might be your device.

**Comment by axstin** [comment]
Closed due to no response from issue author
