### ISSUE TITLE
Cars act weird and unstable

### ISSUE THREAD

**Issue by BYMERTV** [axstin/rbxfpsunlocker#135]
When I use certain cars and using an unlocker, they like fly in one side and are very unstable. The less fps I cap it to, the smaller the problem becomes.

**Comment by InfluxIsDumb** [comment]
Increasing the fps above 60, when some games are designed to be played at 60 or lower(the usual standard) may cause issues if ya didn't know

**Comment by axstin** [comment]
Some Roblox games depend on your framerate for certain calculations. Does this happen in all games? If not, contact the game developer and request support for RFU.
