### ISSUE TITLE
FPS Unlocker doesn't seem to work.

### ISSUE THREAD

**Issue by alonzo165** [axstin/rbxfpsunlocker#136]
I've been using FPS Unlocker for quite some time but for some reason on this update whenever I tried to run it my frames won't go up. I did all the steps but still it wouldn't work, when I try to run it up again it says "FPS Unlocker already running" but no frames have jumped. I usually get about 200-220.

**Comment by PhoenixShay** [comment]
download latest & try - if it's still happening feel free to reopen
