### ISSUE TITLE
Anti-Virus detects a virus in FPS Unlocker.

### ISSUE THREAD

**Issue by RealKinggy** [axstin/rbxfpsunlocker#138]
I know that this "virus" is not real problem but my Anti-Virus won't let me open it, it just deletes it. Could you make that it won't detect "virus" in it? I really need FPS Unlocker. Please try to delete that this what makes my Anti-Virus detect as virus.

**Comment by alexdilon** [comment]
Just whitelist it in your anti virus.

**Comment by axstin** [comment]
Every Anti-Virus is different and I am not able to "fix" RFU so it is not detected by yours. You must add an exclusion yourself (google how to do this for your AV). See [FAQ](https://github.com/axstin/rbxfpsunlocker#FAQ)
