### ISSUE TITLE
my fps unlocker closes my roblox and the program when i launch it

### ISSUE THREAD

**Issue by 4ndyBruh** [axstin/rbxfpsunlocker#139]
Hi i have a problem with the fps unlocker.
When i launch the program from the zip file it just closes my roblox and the fps unlocker itself.
This has never happend before the update on roblox 2 days ago and the new relese of this fps unlocker the 4.1.1.
It does not help to reinstall the fps unlocker or roblox, i have tried 2 times already.

I hope i can get any useful feedback :)

**Comment by axstin** [comment]
Use this issue for updates: https://github.com/axstin/rbxfpsunlocker/issues/133
