### ISSUE TITLE
Annoying physics issue

### ISSUE THREAD

**Issue by Walter-o** [axstin/rbxfpsunlocker#14]
I'm assuming that recently a update to the jumping physics took place because a very annoying bug is taking place when im using rbxfpsunlocker. This only happens after running injector.exe:

Here's a video to show what i mean: https://youtu.be/tnsXEaFtmrI

Link to game if anyone wants to replicate: https://www.roblox.com/games/537413528/Build-A-Boat-For-Treasure

It happens in every game but just incase anyone wants to exactly replicate it. I can't fully confirm it but i think it only happens to R15 characters. But still, some games force R15.

**Comment by PhoenixShay** [comment]
not happening anymore
