### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by IamBadatLife** [axstin/rbxfpsunlocker#141]
Whenever i start a roblox game and start the fps unlocker it runs smoothly but like 5 seconds after it just crashes my game and the launcher it self.. Anybody know why? help?

**Comment by axstin** [comment]
https://github.com/axstin/rbxfpsunlocker/issues/133

**Comment by IamBadatLife** [comment]
? what's that supposed to mean?

**Comment by IamBadatLife** [comment]
can you just tell me if you know how to fix it pls.

**Comment by axstin** [comment]
This is a duplicate issue. Your problem (and a several others' problem) is being discussed in the issue I linked.

**Comment by IamBadatLife** [comment]
where did you link it?
