### ISSUE TITLE
FPS Unlocker gets detected by AntiVirus and closes roblox randomly

### ISSUE THREAD

**Issue by Joaquin916i** [axstin/rbxfpsunlocker#144]
When I open fps unlocker it closes Roblox, and it gets detected by my AntiVirus detected as IDP.Generic

**Comment by dariohells** [comment]
Thats happening to me too... of

**Comment by dariohells** [comment]
>

**Comment by 4ndyBruh** [comment]
happend to me too

**Comment by ThatOneArsenalRetard** [comment]
happens  to me too

**Comment by axstin** [comment]
@Joaquin916i Does temporarily disabling your anti-virus stop the unlocker and Roblox from crashing/closing?

**Comment by ThatOneArsenalRetard** [comment]
axstin ur fps unlocker has idp.alexa.51

**Comment by 4ndyBruh** [comment]
LOL

**Comment by CelestialVindication** [comment]
Try adding an exception in your antivirus for the program's file location. That way, it wouldn't touch RBXFPSUNLOCKER.
