### ISSUE TITLE
new roblox update realse this need to be update 

### ISSUE THREAD

**Issue by farleyeccles** [axstin/rbxfpsunlocker#164]
hey I noticed that roblox was updated recently meaning that robloxfpsunlocker  need to be updated to work with the newest roblox update and I really need this to be able to play roblox on my pc since if I can't use this my pc lags out the game my pc is old from 2012 and I don't have the money to buy a new one this is the only thing that lets me play phantom forces without lagging out could you add away so you don't have to delete the old version like an auto-updater feature that would be great

**Comment by CelestialVindication** [comment]
You seem to be under the impression that rbxfpsunlocker _increases_ your frame rate. This is a common misconception and this program does not actually boost your FPS, but rather unlock it so you can process more frames. This usually produces a smoothing effect which is more pleasing to look at than the generic 60. This program already has an autoupdater, and currently does not need a new one.
