### ISSUE TITLE
can't use fps unlocker

### ISSUE THREAD

**Issue by tintintin8** [axstin/rbxfpsunlocker#166]
when i am opening roblox, the fps doesn't really go up high and it stuck in 60 or below i really want to do know what is happening and please reply to my massage.

**Comment by cheeesy** [comment]
Are you sure your PC is capable of playing Roblox at >60 fps?

**Comment by AmGona** [comment]
The FPS unlocker doesn't boost performance. What it does is it allows Roblox to go over the 60 FPS cap.
