### ISSUE TITLE
Avast Anti-Virus Doesn't Allow Me To Use FPS Unlocker

### ISSUE THREAD

**Issue by ClaytonOwens** [axstin/rbxfpsunlocker#168]
I am aware that Avast reads this as a false-positive and blocks it, and I also understand that this included in F&Q.  BUT, every time I attempt to add an exception to FPS unlocker it doesn't let me and it constantly moves it the virus chest.  I was able to make it work once, but after that, it doesn't.

For anyone who has Avast and has found a workaround, what did you do?

**Comment by Zewwo-Boi** [comment]
You should whitelist the software by going to "Settings" > "General" > Click on "Exceptions" > "File Paths" and then select the folder/exe. and there you go

**Comment by ClaytonOwens** [comment]
I've tried to whitelist it just like that and it still blocks it every
single time.  I have also tried to set my avast to at least ask me what I
want to do with files that come up as threats but I never get the option to
choose, it just automatically moves it to the virus chest.

**Comment by Zewwo-Boi** [comment]
Ok, then you should disable the anti-virus for a certain amount of time. You can do that by clicking on the arrow which is pointing up on the right side of the Hotbar. Click that then you will see an avast logo. Right-click it and I believe there should be a thing called "Disable Anti-virus" or something like that. You can choose the time for it.

**Comment by konig123YT** [comment]
just turn off it
