### ISSUE TITLE
Roblox Update

### ISSUE THREAD

**Issue by Deadninja127** [axstin/rbxfpsunlocker#17]
New Roblox Update Patching FPS Unlocker

**Comment by DarkStyl3R** [comment]
I also have that problem, because of a Roblox update

**Comment by xAnicetus** [comment]
Same here

**Comment by Johnyknowhow** [comment]
Can confirm, game stuck at 60fps and rbxfpsunlocker throwing scan failed errors.

**Comment by say-CS** [comment]
same

**Comment by axstin** [comment]
I've fixed this issue and added some new features. Get the latest release here:
https://github.com/axstin/rbxfpsunlocker/releases
