### ISSUE TITLE
FPS won't go over 60 even though I have activated the program

### ISSUE THREAD

**Issue by Abyasa-ai** [axstin/rbxfpsunlocker#171]
The program was running fine for about 2 days and Roblox was running over 60 fps like it was supposed to, but today even after I ran the program Roblox is now running at max 60 fps. I tried removing the settings file and ran the program again as it's going to make a new settings file but roblox still ran at 60 fps max. I even tried deleting the program and downloading the program again, but the problem still persists.

**Comment by colxurs** [comment]
If you have ROBLOX Studio open, close it. It will then work.

**Comment by axstin** [comment]
Does this issue still occur with the latest version of RFU?

**Comment by NoahHere** [comment]
> Does this issue still occur with the latest version of RFU?

I don't know if this is the same thing but mine just closes down and then pops back up with a red messager reading out "Variable scan failed! This is probably due to a roblox update-- Watch the GitHub for any patches or fix. 

I have the 4.2.0 Version so this shouldn't pop up right?

**Comment by PhoenixShay** [comment]
download the latest version, if it's still happening re-open this issue
