### ISSUE TITLE
FPS not really unlocked?

### ISSUE THREAD

**Issue by khaloodi-s** [axstin/rbxfpsunlocker#1715]
When I'm on the roblox window, FPS is at 60.
Once I hold Alt + Tab, or hover over the preview window over the roblox icon in the taskbar, FPS is in the 500 - 600 range.
I have the FPS cap set to unlimited, and running the app as an administrator.

**Comment by PhoenixShay** [comment]
Can you record a video please?

**Comment by khaloodi-s** [comment]
@PhoenixShay I managed to fix it by referring to an older post. I pressed Alt + Enter and it worked. However, Roblox now runs at 2k and I can't revert it to run at 1080p like previously, meaning text is much smaller on UIs and topbars and things like that, but I do not mind that.

**Comment by khaloodi-s** [comment]
However, every time I tab out and into Roblox, I have to press Alt + Enter, any idea how to fix that?

**Comment by Alpha12343434** [comment]
Yo Khaloodi Can u help me and if u could if u have discord can u add me Its ⸔AL๖ۣۜƤHA⸕ ツ#4902 just copy paste more easier, if u dont have discord can u help me here pls i really need help.

**Comment by axstin** [comment]
https://github.com/axstin/rbxfpsunlocker/issues/1781
