### ISSUE TITLE
How to unstall the fps unlocker?

### ISSUE THREAD

**Issue by Alpha12343434** [axstin/rbxfpsunlocker#1719]
Can someone help me pls idk how to unstall the fps unlocker pls help.

**Comment by killercloudj** [comment]
Mr man Look in the dis of code

**Comment by killercloudj** [comment]
Usage
1 Download the latest release from https://github.com/axstin/rbxfpsunlocker/releases
2 Extract rbxfpsunlocker-x64.zip or rbxfpsunlocker-x86.zip into a folder
3 Run rbxfpsunlocker.exe before or after starting Roblox
4 Enjoy those beautiful frames 👌

**Comment by Alpha12343434** [comment]
What dis of code?

**Comment by axstin** [comment]
See [FAQ!](https://github.com/axstin/rbxfpsunlocker#faq)
