### ISSUE TITLE
Settings keeps appearing on my desktop

### ISSUE THREAD

**Issue by CanadianBanana** [axstin/rbxfpsunlocker#1724]
The settings for the FPS unlocker keeps showing up on my desktop, this happens every time I open the FPS unlocker.
![settings thing](https://user-images.githubusercontent.com/67390188/85617711-b2eecf00-b62d-11ea-913e-2d004970c04b.png)

**Comment by axstin** [comment]
See issue https://github.com/axstin/rbxfpsunlocker/issues/1758
