### ISSUE TITLE
Its saying its a Trojan 

### ISSUE THREAD

**Issue by Blaylay** [axstin/rbxfpsunlocker#1735]
Ok I want to use an fps unlocker because I think that the normal 60 fps is too slow for me, i use a 86x computer and each time i try to download the one for the 86x (64x) it tells me that its a Trojan and its a very severe Trojan. Someone help be why its a Trojan. Extra Information when i download the 32x one its says its fine. All it says is that its doesn't know who made it but its not useable for me.

**Comment by PhoenixShay** [comment]
It’s not a virus. Build the source code yourself if you don’t trust the executables
