### ISSUE TITLE
FPS unlocker in MacOS doesn't work

### ISSUE THREAD

**Issue by guidingkoala** [axstin/rbxfpsunlocker#1736]
This FPS unlocker doesn't work in MacOS as my macbook is incompatible with nothing

**Comment by PhoenixShay** [comment]
It doesn't work because you downloaded a Windows program and tried to run it on something that isn't Windows

**Comment by guidingkoala** [comment]
What is a MacOS program that works for MacOS

**Comment by J4-C** [comment]
Don't think there is a macOS Roblox one
