### ISSUE TITLE
RTX 2070 max q, I7-9750H

### ISSUE THREAD

**Issue by RealUnivers123** [axstin/rbxfpsunlocker#1738]
Roblox game can't reach 144 fps as my refresh rate, with max graphics. How do I get more fps in roblox. Or is the engine too bad and optimization?

**Comment by policetonyR** [comment]
Poor game and poor optimization on roblox

**Comment by axstin** [comment]
From my experience, the Windows 10 store app seems to have worse performance than the regular client if you're using that.
Otherwise, I notice your components appear to be that of a laptop/mobile device which generally speaking perform worse than their desktop counterparts.
