### ISSUE TITLE
Is there a version of this for mac users?

### ISSUE THREAD

**Issue by TheGamerOfGames** [axstin/rbxfpsunlocker#174]
I tried doing everything, downloading wine bottler, extracting it, and it seems there are no other replacements for this program so maybe could you possibly make a version for us mac

**Comment by Zewwo-Boi** [comment]
Nope. I don't think the developer has a device that has MacOS installed... or does he/she?

**Comment by TableFlipper2** [comment]
No, never anyways if there was a mac version. Your 60hz monitor wouldnt be able to even render above 60 fps

**Comment by axstin** [comment]
Unfortunately, there is no version available for Mac users. Please see the FAQ.
