### ISSUE TITLE
No attached processes/failing to inject

### ISSUE THREAD

**Issue by agariomaster10** [axstin/rbxfpsunlocker#1742]
https://youtu.be/N-JHvFvMM8A video of what is happening, this is the second time posting about this problem.
no attached processes, and fps stays at 60. ik that this is a problem that has been happening alot lately but I would like to know if has been fixed yet.

**Comment by agariomaster10** [comment]
![image](https://user-images.githubusercontent.com/65855035/86407838-a6d8c200-bc6a-11ea-9874-0e87176bf913.png)
nothing in console other than watch thread started

**Comment by axstin** [comment]
If you are using the Windows 10 store app, try the latest version of RFU. Issue should be fixed. Let me know if it isn't
