### ISSUE TITLE
My FPS recaps itself whenever I focus on the Roblox window

### ISSUE THREAD

**Issue by synisoffline** [axstin/rbxfpsunlocker#1746]
Pretty much the title. Whenever I try to open the program, it attaches fine, but whenever I click on the Roblox window, it goes back down to 60 FPS, but when I click off of Roblox it goes back to 100-200 FPS. If anyone knows a solution, please reach out to me.

Example: https://gyazo.com/68d42d5600a0d7c06853a0692b0efefe

**Comment by axstin** [comment]
I see this issue a lot. My only guess is Windows or your graphics software capping your FPS for v-sync reasons. Do you have a Nvidia GPU?

**Comment by Omegax15** [comment]
Same thing happens to me. I usually get 240+ FPS and when I click on the window it drops to 60. I have a NVIDIA GPU, so..

**Comment by axstin** [comment]
https://github.com/axstin/rbxfpsunlocker/issues/1883
