### ISSUE TITLE
When i click the downloaded folder, it says "Removed" instead of opening it.

### ISSUE THREAD

**Issue by Cryxcop** [axstin/rbxfpsunlocker#1748]
AAAAAAAAAAAAAAAAAAA HEEEELLLLPPP MEEEE im on 32 bit btw,the 64 bit working fineeee

**Comment by EndergamingVN** [comment]
I think the 32 bit is broken when i download,it says "Deleted" please fix 32 bit

**Comment by axstin** [comment]
Likely your anti-virus, see FAQ.
