### ISSUE TITLE
fps unlocker wont unlock

### ISSUE THREAD

**Issue by MystyIsBreezy** [axstin/rbxfpsunlocker#1749]
Basically i opened the fps unlocker and go to my game (strucid) but the fps doesnt go above 60

**Comment by icywolfL21** [comment]
I did that and go to pf and arsenal and it still doesn’t work

**Comment by Abori** [comment]
If it’s not already, try running it as administrator, not fully sure if this will work, but based on what other comments said, this fixed it. If your problem has nothing to do with that, then idk.

**Comment by icywolfL21** [comment]
I’m on laptop and what am I going to do with FPS unlocker with this?

**Comment by axstin** [comment]
Closed as uninformative and duplicate
