### ISSUE TITLE
Roblox FPS Unlocker 4.2.0 Issue

### ISSUE THREAD

**Issue by jaydengardner12** [axstin/rbxfpsunlocker#1751]
#1747 

So, when I download it, after it downloads, a message pops up in my screen saying "Windows cannot complete this extraction. The destination file could not be created." and then it gives me a message explaining the same thing then it gives me 2 options "Don't run" or "Run anyway" and I Klick run anyways and it takes me to this place file with words and it says "Checking for updates..." and it stays like that forever.

I'm having an extreme lag in Roblox, I need you to please help me. I really want to play Roblox.

My email is jaydengardnerofficial@gmail.com (I have a Lenovo laptop)

**Comment by axstin** [comment]
This sounds like your anti-virus blocking the extraction. Try disabling it or adding an exception (also see FAQ)
