### ISSUE TITLE
Does this program output errors in Roblox Console?

### ISSUE THREAD

**Issue by orange451** [axstin/rbxfpsunlocker#1752]
Hiah! I need some clarification from the author of this program. Will this FPS Unlocker ever output an HTTP 409 Conflict error in the ROBLOX Console? We believe a user in one of our games is using some script injector. We're seeing he's getting a 409 error from a script with a hashed name in the console. He claims it's from this program, I wanted to double check here.

**Comment by PhoenixShay** [comment]
No. This does not have the capabilities to cause a stack trace to appear in the console, it does not interact with the Lua environment in any way.
