### ISSUE TITLE
FPS unlocker dont wanna work for me

### ISSUE THREAD

**Issue by OMAREPIC** [axstin/rbxfpsunlocker#1762]
i saw kreekcraft doing a vid about the fps unlocker and i did all the steps and it dont wanna work
it says "Faild To Connect To GitHub" 
i signed in from along and it dont wanna let me use it 
it opens and does nothing
pls reply my normal fps is like 13-26 :(

**Comment by Yousuf371** [comment]
me too it isnt work for me either

**Comment by kookookatchu** [comment]
All you need to do is just download the program and you dont need videos. Plus fps is doesnt magically just appear after you download this. If your computer wasnt powerful enough to go past the cap of 60 then you never really needed the unlocker. But if you had 60 fps always before then there is a problem.

**Comment by axstin** [comment]
See latest [FAQ](https://github.com/axstin/rbxfpsunlocker/#faq)
