### ISSUE TITLE
FPS Unlocker not working?

### ISSUE THREAD

**Issue by y1nyangy** [axstin/rbxfpsunlocker#1776]
Without FPS unlocker. my games hit their cap at 60fps and with the FPS unlocker it still doesn't make a difference and caps at 60..
I have a 144hz screen, 1660ti mobile, and an i7-9750h, so I'm sure it should be above 60fps if it were unlocked.
I made sure to allow the program in my computer and not be blocked by Windows Defender. As well as download the current latest version (4.2).
The program opens and every thing seems to function except for the actual FPS unlocking part.

**Comment by panda175** [comment]
its not working on mobile iphone or android its still not working pls make a fps unlocker for mobile iphone and android device
