### ISSUE TITLE
Mac users

### ISSUE THREAD

**Issue by Jimmyoofer** [axstin/rbxfpsunlocker#1778]
This isn't really an issue, but I would like the owner to see this and try to make a mac version cause I play a lot of Cs Blox. So If anyone sees this, please leave a comment if there are like any fps unlockers for mac. Thanks!

**Comment by veloszn** [comment]
Yeah I've been trying to search for an fps unlocker for mac and I haven't found one yet because I enjoy playing strucid and I really want an fps unlocker
