### ISSUE TITLE
FPS unlocker is working and FPS is boosted, but still only gives me 60fps

### ISSUE THREAD

**Issue by eonjugg** [axstin/rbxfpsunlocker#1781]
Ran it, did shift+f5 and it tells me that my FPS are consistently above 120. However, the actual gameplay is still at 60fps.

**Comment by axstin** [comment]
What indicates that the "gameplay is still at 60fps"?

**Comment by eonjugg** [comment]
@axstin The game with and without the FPS unlocker has an identical smoothness to it. Shift+F5 says otherwise, but it still appears to be at 60 fps.

**Comment by axstin** [comment]
Entering fullscreen using Alt+Enter has solved this issue for me in the past. Likely a Windows issue. Try it and see if it helps.

**Comment by eonjugg** [comment]
@axstin This worked, thanks!

My only slight issue is that using this method of going into fullscreen scaled the GUI a bit small. Is there any setting I can use (i'm assuming in a roblox config file somewhere) that I can alter it, or should I just deal with it?

**Comment by axstin** [comment]
Glad it helped! I'm going to add this problem to the FAQ when I can.

Do you have a high resolution monitor? Not sure if much can be done without modifying your display settings unless a UI scale setting exists in Roblox's escape menu. Nvidia/AMD control panel may also have the ability to force resolutions for certain applications.
