### ISSUE TITLE
Can't uninstall rbxfpsunlocker

### ISSUE THREAD

**Issue by ImNotKevPlayz** [axstin/rbxfpsunlocker#1788]
I've tried deleting the zip and the exe but none of those worked. The rbxfpsunlocker didn't show up in add or remove programs nor control panel's program and features. It still is running somehow. I checked task manager, it doesn't look like it's running. I checked startup programs, and it wasn't there either. Yet somehow my fps isn't locked.

**Comment by axstin** [comment]
See [FAQ](https://github.com/axstin/rbxfpsunlocker#FAQ)
