### ISSUE TITLE
newest version to the date of the issue will not download as it's registered as a virus

### ISSUE THREAD

**Issue by ARobloxUser** [axstin/rbxfpsunlocker#1789]
so I noticed a new update for the fps unlocker, and I try to download the 64 bit one, as my pc is 64 bit, and it was registered as a virus and did not install. please fix this, as this thing helps my computer run roblox.

**Comment by CrazyKebab** [comment]
Just turn off ur virus protector, download it, then turn it back on again.

**Comment by axstin** [comment]
Please see the FAQ. Use Google or etc. to find how to add an exclusion for RFU to your anti-virus.
