### ISSUE TITLE
Virus problem

### ISSUE THREAD

**Issue by KrummyKraken** [axstin/rbxfpsunlocker#1790]
Avast keeps saying there's a virus in the newest version (4.3.0) Now I know Avast has these problems with detecting "fake viruses". I just wanted to let you know.  
![92815943-be32da80-f392-11ea-810d-e7f2de3da42f](https://user-images.githubusercontent.com/71104303/92815970-cdb22380-f392-11ea-99ee-2d611aaea0e3.png)

**Comment by axstin** [comment]
Is this with the 64-bit or 32-bit version of RFU? The 32-bit version has many false positives (for reasons unbeknownst to me) and there's not much I can do.

**Comment by GCxplay** [comment]
I'm having the same problem with the 64-bit version.

**Comment by KrummyKraken** [comment]
The 64-bit version was acting up for me.

**Comment by KrummyKraken** [comment]
> 
> 
> Is this with the 64-bit or 32-bit version of RFU? The 32-bit version has many false positives (for reasons unbeknownst to me) and there's not much I can do.

The 64-bit version was acting up for me.

**Comment by axstin** [comment]
The VirusTotal for the 64-bit version can be found here: https://www.virustotal.com/gui/file/fc3f95654a181920f05056063bce148fdad38c4b2cd28fa3870bd4e071c564d8/detection

Avast & etc. don't seem to have a problem with it according to this? For now, add an exclusion to your AV and mark it as a false-positive if possible. Hopefully the issue resolves itself over time.

**Comment by CrazyKebab** [comment]
My virus protector doesn't detect it as a virus. Turn ur protector off, activate rbxfpsunlocker, then turn it back on again.

**Comment by heryjumansyah** [comment]
avast is have many false positive for certain programs and its heavy usage on ram ,i am not recommend to use avast because it ,now i use Kaspersky for my antivirus and i use robloxfpsunlocker without interference

**Comment by PhoenixShay** [comment]
Malwarebytes is a good AV if you need a recommendation. We can't help with false positives unless you want to donate towards getting a digital certificate to sign FPSUnlocker with
