### ISSUE TITLE
Roblox crash when using FPS Unlocker

### ISSUE THREAD

**Issue by Darkiuke** [axstin/rbxfpsunlocker#1794]
Whenever I am starting my roblox and I open my FPS Unlocker my Roblox suddenly crashes. Some times, it told me "rbxunlocker.exe will be compressed only after closing the application using it. Modifications will be lost if you close WinRAR before that."

**Comment by Darkiuke** [comment]
I tried many times to even reinstall it, and restart my PC, nothing happened.

**Comment by axstin** [comment]
This is very likely due to your anti-virus. Try disabling it temporarily or adding an exclusion. It is also recommended to extract the zip file, not run RFU from inside.
