### ISSUE TITLE
Chrome says its not commonly downloaded and may be virus 

### ISSUE THREAD

**Issue by SoggyMangoSteam** [axstin/rbxfpsunlocker#1796]
First of all, "false positive" is not going to persuade me to think this is safe. 2. I prefer things that arent a virus
So yh description says it all tbf

**Comment by PhoenixShay** [comment]
So don't use it then. Why do you think we care?

**Comment by axstin** [comment]
See FAQ: this project is open source and you are free to compile it yourself.
