### ISSUE TITLE
ROBLOX Studio doesn't work - New update

### ISSUE THREAD

**Issue by colxurs** [axstin/rbxfpsunlocker#180]
ROBLOX Studio doesn't work with ROBLOX FPS unlocker for me. and I think it's for everyone else as well.

This probably doesn't work anymore, due to ROBLOX updates. Update the FPS unlocker, please!

**Comment by AmGona** [comment]
Yeah, quite annoying. One thing I use the FPS unlocker for is because roblox stutters, even though it displays as 60 FPS, but when I use the unlocker it stops. It stutters due to a weird bug with my monitors refresh rate, but eh. Quite annoying how it broke with studio.

**Comment by axstin** [comment]
Fixed in v4.2.0!
