### ISSUE TITLE
It doesn't work it it keeps me on low fps.

### ISSUE THREAD

**Issue by Samsonig** [axstin/rbxfpsunlocker#1803]

**Comment by thyerue5tjt** [comment]
do you have "unlock roblox player" on?

**Comment by Samsonig** [comment]
Yeah

**Comment by thyerue5tjt** [comment]
is the fps cap on none?

**Comment by Samsonig** [comment]
> is the fps cap on none?

**Comment by Samsonig** [comment]
Nope i picked 240 fps and it keeps me on low fps

**Comment by thyerue5tjt** [comment]
mmmm

**Comment by thyerue5tjt** [comment]
you should put it on none so it can go over 240 fps, if you want it that is

**Comment by thyerue5tjt** [comment]
maybe it will fix it too

**Comment by thyerue5tjt** [comment]
...or the new version is broken, lemme join arsenal and check

**Comment by Samsonig** [comment]
I deleted it and downloaded it multiple times and it doesn't work i put it on none and it doesn't work

**Comment by thyerue5tjt** [comment]
mm

i joined arsenal and its good for me

**Comment by thyerue5tjt** [comment]
maybe your roblox version is bad, try reinstalling roblox

**Comment by thyerue5tjt** [comment]
_i mean its fine for me_

**Comment by Samsonig** [comment]
i uninstalled roblox 2 days ago and installed it again

**Comment by thyerue5tjt** [comment]
try doing it rn

**Comment by Samsonig** [comment]
alright

**Comment by thyerue5tjt** [comment]
_e_

**Comment by PhoenixShay** [comment]
You really don’t need to post multiple comments to get your point across

**Comment by Samsonig** [comment]
Still doesn't work

**Comment by Samsonig** [comment]
Multiple people got this issue soo idk  it might be the new update breaking it for some people

**Comment by axstin** [comment]
What is your FPS before using RFU?

**Comment by Samsonig** [comment]
30-40 if i put graphics to half it gets me to 15 fps

**Comment by axstin** [comment]
RFU is an unlocker, not a performance booster. Please see [FAQ "I used this unlocker and my framerate is the same or below 60. Why?"](https://github.com/axstin/rbxfpsunlocker#faq)
