### ISSUE TITLE
Changed Threat

### ISSUE THREAD

**Issue by SuperMember1** [axstin/rbxfpsunlocker#1804]
Before it was Trojan:Win32/CredentialAccess!rfn then it changed to Trojan:Win32/Woreflint.A!cl

What really happened?

Antivirus don't find 64x virus but 32x.
Please make it so 32x doesnt detected virus

**Comment by PhoenixShay** [comment]
There is no virus. If you want to pay for a digital certificate to sign the application to prevent detections, let us know
