### ISSUE TITLE
"Variable scan failed!" error message

### ISSUE THREAD

**Issue by DoIoco** [axstin/rbxfpsunlocker#1807]
![Screenshot 2020-09-15 172318](https://user-images.githubusercontent.com/71353112/93266830-ae433e00-f778-11ea-9c00-cdf0968ac54c.png)

**Comment by RojoEFE** [comment]
same :(

**Comment by DoIoco** [comment]
ok

**Comment by axstin** [comment]
What is your FPS before using the unlocker?

**Comment by axstin** [comment]
See latest FAQ
