### ISSUE TITLE
Is FPS Unlocker Safe?

### ISSUE THREAD

**Issue by Derzree** [axstin/rbxfpsunlocker#181]
Hello, im wondering if i could use this on Phantom Forces because im worried i might get banned.
Ive used this on some games so  it works fine but i would like to know if this is safe to use and doesnt trigger anti cheats

**Comment by kiranhart** [comment]
Yes it's save, It might trigger your anti-virus. Which will cause it to say that it might be dangerous but its not. As for phantom forces, lot's of people use it, you're not going to get banned. If they really wanted people to stick to 60fps, that will have been fixed long ago.

**Comment by axstin** [comment]
RFU may trigger some naive anti-cheats, but Phantom Forces' anti-cheat isn't one of them. You should be fine.
