### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by fartmasterandre2008** [axstin/rbxfpsunlocker#1813]
it does allow my fps to go above 60, but it does not keep my fps at what i selected. for example if i set it to 60 fps it still goes down to the 10s and 20s. im not sure if its supposed to keep my fps high or let my fps go above 60, or both

(my laptop is laggy and isnt the best so it might be my fault)

**Comment by axstin** [comment]
Roblox FPS unlocker is an unlocker, not a booster... please see the [FAQ](https://github.com/axstin/rbxfpsunlocker#faq)
