### ISSUE TITLE
Variable Scan Failed strikes again. WHY????????

### ISSUE THREAD

**Issue by robloxianstudio123** [axstin/rbxfpsunlocker#1814]
not again.
![variablescanfailedstrikesagain](https://user-images.githubusercontent.com/63188671/94147692-ebdd5080-fe75-11ea-900f-d0ff438ef9f8.png)
WHY?????????
Do i have to reinstall Roblox FPS Unlocker or delete it forever?
reference post from: #1807

**Comment by robloxianstudio123** [comment]
@axstin fix this issue (again), once it's fixed (again), please close the issue.
- @robloxianstudio123

**Comment by axstin** [comment]
Please don't create duplicate issues, reply in the issue you referenced. Is your FPS 60 before running RFU?
