### ISSUE TITLE
Viruses with the newest version of FPS Unlocker

### ISSUE THREAD

**Issue by StallerBait** [axstin/rbxfpsunlocker#1815]
Yo, just a thing, your FPS Unlocker 64 is giving off 1 virus, while the 32-bit version is giving off **33**

The hell's going on?

[https://i.gyazo.com/4b63b77b0a9cc8388a65dbd0acbc2d40.png](url)
[https://i.gyazo.com/c07311e0d7ea6da6192a013d8232e794.png](url)

**Comment by PhoenixShay** [comment]
If you think theres viruses, don’t use it. There’s no malware in fpsunlocker.
