### ISSUE TITLE
This version does not work!

### ISSUE THREAD

**Issue by KirbotakuXD** [axstin/rbxfpsunlocker#1820]
I only have 2 problems.

1. Roblox FPS Unlocker 4.3.0 crashes Roblox.

2. When Roblox crashes me, the Roblox FPS Unlocker 4.3.0 removes itself.

Thanks for reading it and I hope you can solve it.

**Comment by axstin** [comment]
This is due to your anti-virus: try temporarily disabling it or adding an exception.
