### ISSUE TITLE
Slow loading, High Ping

### ISSUE THREAD

**Issue by canekicker** [axstin/rbxfpsunlocker#1823]
Please tell me what I have to do, I don't have a bad CPU. My GPU is decent. However my ping goes up to unexpected amounts and slows down loading as well as removing loaded things in Roblox.

**Comment by photonbeam17** [comment]
Check this issue; it sounds similar to yours.

[https://github.com/axstin/rbxfpsunlocker/issues/275](url)

**Comment by axstin** [comment]
Duplicate, see: https://github.com/axstin/rbxfpsunlocker/issues/275
