### ISSUE TITLE
Can you add a feature where it makes Roblox utilize memory better?

### ISSUE THREAD

**Issue by welovediscord99** [axstin/rbxfpsunlocker#1825]
I always keep lagging in Roblox games even with 12GB of RAM, and you know what? Roblox only uses 600-900 MB of my RAM on average. It's honestly frustrating me, can you also make it so Roblox utilizes memory better and uses atleast 4-5GB like most games like Minecraft and Yandere Simulator do?

**Comment by Spidy123222** [comment]
I would also like something like this also!

**Comment by axstin** [comment]
This is something Roblox has to work on. Nothing I can do. It should also be noted that higher RAM usage != better performance.
