### ISSUE TITLE
when i open fpsunlocker.exe 

### ISSUE THREAD

**Issue by xxxfpsunlocker25xxx** [axstin/rbxfpsunlocker#1831]
when i open fpsunlocker it does appear on the taskbar for a sec, but for 4 sec its now gone. pls help on this issue. (i was gonna update)

**Comment by bbzlazer** [comment]
Should be on bottom right with the arrow facing up (don't know what it's called).

It does work though

**Comment by axstin** [comment]
Likely your Anti-Virus closing the process. Please see FAQ.
