### ISSUE TITLE
Already running?

### ISSUE THREAD

**Issue by Korayatalay** [axstin/rbxfpsunlocker#1842]
When I try to open the fps unlocker, I get an error message saying that it's already running, although it doesn't appear to be open in my taskbar. Somehow it did appear on my taskbar once, but it was still capped at 60, even though it was set to "none". Any thoughts on why this is happening? I have an AMD Ryzen 9 3900 12-Core Processor with 3.09GHz if that helps.

**Comment by antlerblox** [comment]
Go to Task Manager. Scroll down to the background task "rbxfpsunlocker."
Right click, and press End Task. Reopen fpsunlocker. It should work!

**Comment by Korayatalay** [comment]
I just waited a day and then reinstalled it, it works now! Thanks for the suggestion anyways

**Comment by antlerblox** [comment]
Of Course!
