### ISSUE TITLE
roblox update error

### ISSUE THREAD

**Issue by shadowspike74** [axstin/rbxfpsunlocker#1843]
today (17/10/2020) I got this error when using the Robloxfpsunlocker due to a ROBLOX update yesterday it was fine but now I'm getting errors in the console is there anyway to fix this? 

Checking for updates...
Minimizing to system tray in 2 seconds...
Watch thread started
Injecting into new process 0000000000000538 (pid 1060)
ProcUtil::GetModuleInfo: buffer = C:\Users\*****\AppData\Local\Roblox\Versions\version-d25d44458f014535\RobloxPlayerBeta.exe
ProcUtil::FindModuleInfo: path = C:\Users\*****\AppData\Local\Roblox\Versions\version-d25d44458f014535\RobloxPlayerBeta.exe
ProcUtil::FindModuleInfo: info.path = C:\Users\*****\AppData\Local\Roblox\Versions\version-d25d44458f014535\RobloxPlayerBeta.exe
[0000000000000538] Process Base: 0000000000F10000
[0000000000000538] GetTaskScheduler: 0000000001A5C740
[0000000000000538] Scheduler: 00000000067A0528
New size: 1
[0000000000000538] Scheduler: 00000000067A0528
[0000000000000538] Scheduler: 00000000067A0528
[0000000000000538] Scheduler: 00000000067A0528
[ERROR] Variable scan failed! This is probably due to a Roblox update-- watch the github for any patches or a fix.

**Comment by ItzVaio** [comment]
i would get that error in my serviced computer but it only says a little then the error

**Comment by bbzlazer** [comment]
Please codeblock 
@shadowspike74

**Comment by axstin** [comment]
See FAQ on Variable scan failed errors
