### ISSUE TITLE
When I open fps unlocker my ping goes really really high idk why :(

### ISSUE THREAD

**Issue by XxAbdurrahmanxX10** [axstin/rbxfpsunlocker#1849]

**Comment by antlerblox** [comment]
Can I have your computer specs? It might just be computer slowness.

**Comment by XxAbdurrahmanxX10** [comment]
> Can I have your computer specs? It might just be computer slowness.

Its l ntel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz   2.70 GHz

**Comment by XxAbdurrahmanxX10** [comment]
and when i open fps unlocker my ping goes really high and then stays there

**Comment by XxAbdurrahmanxX10** [comment]
Pls help me

**Comment by bbzlazer** [comment]
How are you checking ping

**Comment by antlerblox** [comment]
Check your GPU drivers. It could be a problem with the driver software. Maybe turn off Lag Reducer, and Virtual Super Graphics.
