### ISSUE TITLE
(Request) Add extra fps options.

### ISSUE THREAD

**Issue by TheGhost567** [axstin/rbxfpsunlocker#185]
Option to add custom fps settings, like 15 frames for slowing a game down to process what is going on. (For example in a cutscene or tight platforming segments (Could be considered cheating by some))

**Comment by alexdilon** [comment]
**4. Can I set a custom framerate cap?**
Custom framerate limits can be set by changing the FPSCap value inside the settings file located in the same folder as rbxfpsunlocker.exe and reloading settings (RFU->Load Settings). Changing the cap with RFU's menu will reset/overwrite this value.

**Comment by TheGhost567** [comment]
> **4. Can I set a custom framerate cap?**
> Custom framerate limits can be set by changing the FPSCap value inside the settings file located in the same folder as rbxfpsunlocker.exe and reloading settings (RFU->Load Settings). Changing the cap with RFU's menu will reset/overwrite this value.

That is a temporary solution, requiring roblox to be restarted every time you want to input a new custom value, i would love for there to be a permanent solution, for example, an empty slot to be added and able to set custom fps with a slider or a text box.

**Comment by axstin** [comment]
I'll look into adding this for a future update

**Comment by axstin** [comment]
Moving to https://github.com/axstin/rbxfpsunlocker/issues/1938
