### ISSUE TITLE
FPS still DROPS

### ISSUE THREAD

**Issue by Plucify** [axstin/rbxfpsunlocker#1859]
MY FPS unlocker donesn't react or work during Roblox Arsenal, I've downloaded the latest one and It's still bugged, I'm not quite sure If there is any requirements for it to work, youtubers say you need a strong pc, others say It's bugged, Is this a PC onlyu thing? or what, MY FPS always drops, and I've been told countless times to get this, atlast It doesn't work, I'll send a snip of my laptop specs and blur out the peronsal info to see If there's somthing wrong, or my laptop Isn't strong enough. Heads up I'm using HP laptop. My laptop use to have alot of unesscary things on it, so I've factor reseted my WHOLE laptop, and It runs faster. Problem is fps unlock ain't worker! 
![lastin](https://user-images.githubusercontent.com/73706595/97720174-d89a5200-1abf-11eb-9f8e-e0e0f36f01ea.PNG)

**Comment by PhoenixShay** [comment]
This unlocks your FPS, it does not boost your FPS.
