### ISSUE TITLE
Not able to set custom FPS cap

### ISSUE THREAD

**Issue by CheeseCakeSnake** [axstin/rbxfpsunlocker#1863]
Im trying to set a FPS cap lower then 30, how ever, the .exe doesnt download with the source which has the settings in it (they are separate), and you cant even edit the settings folder, it shows that current fps cap is like at 120.000000 but im not allowed to change out the numbers.

**Comment by Cystax** [comment]
Did you download the whole thing, not just the .exe? It should come with a .txt file named settings.

**Comment by axstin** [comment]
Use your favorite text editor to open the `settings` file after RFU has run at least once and edit the 'FPSCap' variable. Then, click `tray icon->Load Settings`.
