### ISSUE TITLE
put it on Mac please

### ISSUE THREAD

**Issue by chilleryzz** [axstin/rbxfpsunlocker#1867]
PLEASE PUT THIS ON MACBOOK! I REALLY WANT TO PLAY BUT IT IS TOO LAGGY. PLEAAASSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEee.     >:(((

**Comment by bbzlazer** [comment]
Close: Not an issue, It was said in FAQ that this was not going to be ported by the original creator
