### ISSUE TITLE
Framerate capped to 60

### ISSUE THREAD

**Issue by grandeAunderA** [axstin/rbxfpsunlocker#1869]
ok so i have read the FAQ and created and account just to submit my issue. The old version i was using gave me 240 FPS i have a gaming pc. but when i launch the new one ( 4.3.0 ) its still remains 60. I have reinstalled it numerous times. I am saying thios cause my Roblox is quite lagy now and when i had 240 FPS with the older version it was really smooth.

**Comment by ShadowmanWasTaken** [comment]
Experienced the same problem with the new version. I think I've found a fix. Try pressing Alt + Enter on your keyboard two times and you should see your FPS get unlocked in fullscreen.

**Comment by PhoenixShay** [comment]
Do you have a video of this happening?

**Comment by ShadowmanWasTaken** [comment]
![2020-11-21 07-15-58](https://user-images.githubusercontent.com/74573345/99877326-563b1480-2bcb-11eb-8cbe-0a5318b64781.gif)
Video is a bit choppy because I had to convert it into a gif but it basically shows how the FPS gets capped when you go into Fullscreen.

**Comment by axstin** [comment]
@ShadowmanWasTaken What's your GPU? How are you entering fullscreen?

**Comment by SpocckceDelton** [comment]
Im having the same problem too!

**Comment by ShadowmanWasTaken** [comment]
@axstin I currently have Intel HD Graphics 5500 on my laptop and I simply press F11 to enter fullscreen.

**Comment by axstin** [comment]
@ShadowmanWasTaken Try disabling Vsync in your Intel graphics control panel: https://www.intel.com/content/www/us/en/support/articles/000005552/graphics.html

**Comment by ShadowmanWasTaken** [comment]
@axstin THANK YOU SO MUCH! I updated my Intel HD Graphics driver to the lastest version, did the steps to disable Vsync and now the rbxfpsunlocker is working perfectly in fullscreen! 👍

**Comment by axstin** [comment]
Great! Forgot this was actually @grandeAunderA 's issue so I'll leave it open. @grandeAunderA what is your GPU?

**Comment by axstin** [comment]
Closing this issue for now, please see pinned post: https://github.com/axstin/rbxfpsunlocker/issues/1883
