### ISSUE TITLE
The best Roblox fps Unlocker

### ISSUE THREAD

**Issue by LolalrikofficialYT** [axstin/rbxfpsunlocker#1873]
Closed

**Comment by bbzlazer** [comment]
Please close: not an issue, nor a request for improvement

**Comment by LolalrikofficialYT** [comment]
Ok , btw can u make the frames higher for rtx users

**Comment by bbzlazer** [comment]
By closing it, I don't mean editing the message to be closed, i mean going to the issue and deleting/closing it.

I am surprised how many people make an account just to ask a question that is easily answered.
