### ISSUE TITLE
Roblox FPS Unlocker only working when alt-tabbed on GTX 1080

### ISSUE THREAD

**Issue by JpNjeim2** [axstin/rbxfpsunlocker#1877]
So what is going on? When I open roblox and have the FPS unlocker running it only unlocks the fps when I'm alt-tabbed out of roblox, I've tried setting permissions to admin and tried using windowed roblox and tried reinstalling multiple times and tried both the 32 and 64 bit and nothing has fixed it. Please help ASAP as I need to unlock my fps for my next game tourney. Thank you!

**Comment by axstin** [comment]
What GPU do you own?

**Comment by JpNjeim2** [comment]
I have a Nividia GTX 1080 OC

**Comment by axstin** [comment]
This might be related to your Nvidia settings. Try messing with the Nvidia control panel and disabling any Vsync options for Roblox

**Comment by axstin** [comment]
Closing issue, move discussion to: https://github.com/axstin/rbxfpsunlocker/issues/1883
Thanks
