### ISSUE TITLE
It doesnt work!

### ISSUE THREAD

**Issue by SpocckceDelton** [axstin/rbxfpsunlocker#1879]
I turned on the fps counter in roblox and its still between a 60 or a 30 fps. It used to work back in v4.2.0 but in v4.3.0 it stopped showing the 240 fps, pls fix this or else this is a scam!

**Comment by SpocckceDelton** [comment]
Im switching back to v4.2.0 before they broke it

**Comment by axstin** [comment]
sorry, no refunds! please follow the issue guidelines
