### ISSUE TITLE
not getting higher fps and cant see running faster

### ISSUE THREAD

**Issue by hongplayzexe** [axstin/rbxfpsunlocker#188]
pls fix asap i am on a 64 bit and my computer is 64 bit

**Comment by TableFlipper2** [comment]
Kid, this isn't an FPS BOOSTER holy shit doesn't matter what architecture your pc is. The reason you can’t see a higher fps is because of your monitors refresh rate. How are people like you this fucking retarted.

**Comment by Mudock-Yatho** [comment]
fps booster dun werk pleas fax

**Comment by ty69** [comment]
my fps dun go up fps booster bad!!

**Comment by CelestialVindication** [comment]
why fps no go up? me try program and not work. program bad! delete now!

**Comment by Zewwo-Boi** [comment]
Answer: This is an fps UNLOCKER. Not a booster. The program just unlocks the fps which means you will get fps different from 60 fps which Roblox locked to. READ THE DESCRIPTION!!!!!!

**Comment by Sinful-9149** [comment]
fps booster no wurk pls fix me wan refund!!

**Comment by Mudock-Yatho** [comment]
mUH raspberry Pi duN boOst fPs stiLl at 3fps!!! aUstin bAd evil maN makinG raTs!

**Comment by hongplayzexe** [comment]
ok, so its not a fps booster, well can you give me andy links for a fps booter,

**Comment by Zewwo-Boi** [comment]
> ok, so its not a fps booster, well can you give me andy links for a fps booter,

You're not understanding. There is no FPS booster. Even if there is, your computer can throttle.
