### ISSUE TITLE
When I open up the fps unlocker, it just says it's already running?!?

### ISSUE THREAD

**Issue by DaD0ge** [axstin/rbxfpsunlocker#1885]
For some reason, when I open up the fps unlocker, it just says it's already running, and I don't know how to fix it. Help!

**Comment by toastedtoastytoast** [comment]
The same thing is happening to me

**Comment by BotLobbyKid** [comment]
Look in the bottom right and open up hidden icons. If you already see the rbxfpsunlocker icon, that means it is already running.

**Comment by DaD0ge** [comment]
Thanks so much! I didn't look there.

**Comment by BotLobbyKid** [comment]
No problem!
