### ISSUE TITLE
When I use the fps unlocker in Arsenal, everything turns small.

### ISSUE THREAD

**Issue by DaD0ge** [axstin/rbxfpsunlocker#1888]

**Comment by DaD0ge** [comment]
Now whole games turn small, anybody know what to do?

**Comment by bbzlazer** [comment]
Not related to FPS Unlocker, but you pressed alt+enter

**Comment by axstin** [comment]
Please elaborate on what "everything turns small" means.

**Comment by DaD0ge** [comment]
No, it's okay. The issue stopped. But before, items, the chat box, and player list all shrunk. I may have hit something that made it that way. It looked all zoomed out, but now it's good. No more problems.

**Comment by LiterallyChris** [comment]
That was because you deleted roblox files, thats not the unlocker.
