### ISSUE TITLE
Its not working when it said its already running.

### ISSUE THREAD

**Issue by RandomRainer** [axstin/rbxfpsunlocker#1898]
so I was playing roblox and then I tried to put the fps unlocker, but when I checked in game, I had 60 fps.
Idk if theres a bug or theirs something wrong with my PC.Please send an issue if you have the same problom.thank you if your reading this

**Comment by RandomRainer** [comment]
Here i'll even show it on my YouTube channel
 Video link
https://youtu.be/Yvc9PVnHaW0

**Comment by axstin** [comment]
RFU is already running (click the little arrow bottom right of your taskbar to see RFU's icon). If your cap is set to None but you are still at 60fps, see this issue: https://github.com/axstin/rbxfpsunlocker/issues/1883
