### ISSUE TITLE
FPS not unlocking

### ISSUE THREAD

**Issue by ShosNov** [axstin/rbxfpsunlocker#1899]
When I use the unlocker it unlocks the fps for about a game or few of Arsenal then won't work anymore, and due to it recapping fps I've come to the conclusion it creates a gliding effect on my mouse. So the problem is when I tab out of Roblox my fps uncaps but when I tab back in its back to 30. 
Images to help better explain
Tabbed out: http://prntscr.com/vxx4oa
Tabbed in: http://prntscr.com/vxx4wl

**Comment by midmm1** [comment]
either you have to many apps open or the code is broken

**Comment by axstin** [comment]
See pinned issue: https://github.com/axstin/rbxfpsunlocker/issues/1883
