### ISSUE TITLE
FPS Issue

### ISSUE THREAD

**Issue by Lunonius** [axstin/rbxfpsunlocker#19]
Not sure if it is only occurring for me or not but, when I am using the FPS unlocker my FPS only goes from 60 to the 100's opposed to previous versions of the FPS unlocker I could easily hit 300-500 FPS. I went to the list of FPS caps and used the "240" cap which in fact allowed my FPS to then shoot up to 240, but when I set it to "None" meaning NO fps cap, I am stuck in the 100's. My GPU is a 1060 and I use this application to prevent screen tearing and stutter I would usually get from ROBLOX. Not sure if its me or the application but a fix or solution would be much appreciated!

**Comment by Pokl1** [comment]
not sure if it's just me but no matter what settings my framerate is locked at 60, even after clicking load settings.  I have tried with native v-sync on and off.

75hz

https://imgur.com/atxgQaq

**Comment by axstin** [comment]
This might have something to do with the new method I'm using to uncap framerate. Last Roblox update they removed DebugGraphicsVsync, a flag the old method depended on. The new method works by changing a minimum frame time value (set to 1/60 by default) in their TaskScheduler. It should also be noted the "None" option isn't actually infinite and sets the aforementioned variable to 1/1000000 (1M cap).

Unfortunately, this new method works fine for me so this issue may be hard to solve:
https://streamable.com/333ty
I'm using Windows 10 Build 17134 with 75hz monitors and an AMD R9 390 GPU.

Anyway, I'll try adding some things to help debug.

**Comment by axstin** [comment]
@Lunonius @Pokl1 Test version with added debug prints (see console):
[rbxfpsunlocker-3.0-p1.zip](https://github.com/axstin/rbxfpsunlocker/files/2475704/rbxfpsunlocker-3.0-p1.zip)

Post the output here and I'll see if it reveals anything

**Comment by Pokl1** [comment]
> @Lunonius @Pokl1 Test version with added debug prints (see console):
> [rbxfpsunlocker-3.0-p1.zip](https://github.com/axstin/rbxfpsunlocker/files/2475704/rbxfpsunlocker-3.0-p1.zip)
> 
> Post the output here and I'll see if it reveals anything

https://imgur.com/a/A3A25VE

**Comment by Pokl1** [comment]
I am using DX9 btw, address could possibly be different?

**Comment by axstin** [comment]
@Pokl1 
That would be it. The FPS unlocker hooks this function: 
https://docs.microsoft.com/en-us/windows/desktop/api/dxgi/nf-dxgi-idxgiswapchain-present
which is apart of D3D11.

@Lunonius 
You could try setting a custom cap if "None" isn't working as intended. Open your settings file, change FPSCap's value to something over 240, and then restart the unlocker or click "Load Settings" in the unlocker's menu.

**Comment by Pokl1** [comment]
@axstin 
do you believe unlocking fps with dx9 on roblox is still possible without that function?  i haven't looked at the dx9 api in awhile

**Comment by axstin** [comment]
It's definitely possible but I'd have to add code for a D3D9 hook. My Roblox uses D3D11 and D3D9 is pretty outdated so that's what I wrote the unlocker for. How are you using D3D9? Can you switch to 11?

**Comment by Pokl1** [comment]
currently my gpu only supports up to dx9. in version 2.0 of your unlocker this has worked in studio, you can change studio's rendering technique by going into file > settings > rendering > graphics mode

this requires studio to reopen for dx9 to be enabled if a place has already been opened and closed

**Comment by Lunonius** [comment]
By changing the settings under "240" and changing it to 500, everything works fine now, do these settings revert back after closing the application or do they remain the same as I put them?

**Comment by Pokl1** [comment]
> By changing the settings under "240" and changing it to 500, everything works fine now, do these settings revert back after closing the application or do they remain the same as I put them?

i believe you can set the file to read-only to prevent any changes

**Comment by axstin** [comment]
> do these settings revert back after closing the application or do they remain the same as I put them?
If you change the cap in the dropdown menu the FPSCap setting is overwritten.

And @Pokl1 I'll work on adding D3D9 support in the next update.

**Comment by Pokl1** [comment]
> > do these settings revert back after closing the application or do they remain the same as I put them?
> > If you change the cap in the dropdown menu the FPSCap setting is overwritten.
> 
> And @Pokl1 I'll work on adding D3D9 support in the next update.

thank you!  i really appreciate it

**Comment by Pokl1** [comment]
@axstin
there's a small issue with opening the .exe file from the top bar in explorer, when opening it like this the .dll file won't be detected.  this does not occur when using the same method inside the folder

https://imgur.com/a/vZrdjdg

**Comment by YTNobita** [comment]
> This might have something to do with the new method I'm using to uncap framerate. Last Roblox update they removed DebugGraphicsVsync, a flag the old method depended on. The new method works by changing a minimum frame time value (set to 1/60 by default) in their TaskScheduler. It should also be noted the "None" option isn't actually infinite and sets the aforementioned variable to 1/1000000 (1M cap).
> 
> Unfortunately, this new method works fine for me so this issue may be hard to solve:
> https://streamable.com/333ty
> I'm using Windows 10 Build 17134 with 75hz monitors and an AMD R9 390 GPU.
> 
> Anyway, I'll try adding some things to help debug.

i have

**Comment by YTNobita** [comment]
it says **failed to connect github** help me reply me plz
