### ISSUE TITLE
rblxfpsunlocker crashes ROBLOX Player and itself.

### ISSUE THREAD

**Issue by SnaKe15** [axstin/rbxfpsunlocker#190]
When I start, rblxfpsunlocker after starting ROBLOX it crashes immediately while playing Arsenal. Please help.

**Comment by snowsxx** [comment]
Its not updated yet, so it shouldn't work right now.

**Comment by axstin** [comment]
Does this problem still occur with the latest version of RFU?

**Comment by SnaKe15** [comment]
> Does this problem still occur with the latest version of RFU?

**Comment by SnaKe15** [comment]
> Does this problem still occur with the latest version of RFU?

I'll try.

**Comment by SnaKe15** [comment]
> Does this problem still occur with the latest version of RFU?

It worked for one day, but today it crashed roblox and deleted itself from the downloads.

**Comment by PhoenixShay** [comment]
sounds like it was picked up by your antivirus, make sure you disable it or add fpsunlocker as an exception
