### ISSUE TITLE
My fps unlocker says that its already running but its not working.

### ISSUE THREAD

**Issue by RandomRainer** [axstin/rbxfpsunlocker#1905]
so I was playing Roblox and then I tried to put the fps unlocker, but when I checked in game, I had 60 fps.
I don't know if theirs a bug or theirs something wrong with my PC.Please send an issue if you have the same problem.Thank you if your reading this

**Comment by RandomRainer** [comment]
Here I'll even show it on my YouTube channel
Video link
https://youtu.be/Yvc9PVnHaW0

**Comment by Scarfdee** [comment]
Here, maybe go to task manager and end the FPS unlocker's task. Then try opening the unlocker again.

**Comment by RandomRainer** [comment]
Do I go to details?

**Comment by RandomRainer** [comment]
oh nvm

**Comment by PhoenixShay** [comment]
Please don’t make multiple issues for the same problem
