### ISSUE TITLE
Failed to process baseeeeee

### ISSUE THREAD

**Issue by FAILEDTOPROCESSBASE** [axstin/rbxfpsunlocker#1909]
![image](https://user-images.githubusercontent.com/75902907/101989302-2356de80-3ca8-11eb-87a5-acd727e6354d.png)

**Comment by Ewanophobia** [comment]
What's your version of Windows 10 (and is it 64 bit or 30 bit).

See here if unsure: https://support.microsoft.com/en-us/office/determine-whether-your-computer-is-running-a-32-bit-version-or-64-bit-version-of-the-windows-operating-system-aac162a1-0cb3-46f2-888f-2f22897396ce#:~:text=Click%20Start%2C%20type%20system%20in,the%20System%20type%20under%20System.

**Comment by FAILEDTOPROCESSBASE** [comment]
it is a 64 bit it has worked for like 5 months but yesterday it doesent work

**Comment by FAILEDTOPROCESSBASE** [comment]
> What's your version of Windows 10 (and is it 64 bit or 30 bit).
> 
> See here if unsure: https://support.microsoft.com/en-us/office/determine-whether-your-computer-is-running-a-32-bit-version-or-64-bit-version-of-the-windows-operating-system-aac162a1-0cb3-46f2-888f-2f22897396ce#:~:text=Click%20Start%2C%20type%20system%20in,the%20System%20type%20under%20System.

![RobloxScreenShot20201213_122606505](https://user-images.githubusercontent.com/75902907/102020261-a8adc200-3d80-11eb-963c-08a7b669594d.png)

**Comment by FAILEDTOPROCESSBASE** [comment]
> What's your version of Windows 10 (and is it 64 bit or 30 bit).
> 
> See here if unsure: https://support.microsoft.com/en-us/office/determine-whether-your-computer-is-running-a-32-bit-version-or-64-bit-version-of-the-windows-operating-system-aac162a1-0cb3-46f2-888f-2f22897396ce#:~:text=Click%20Start%2C%20type%20system%20in,the%20System%20type%20under%20System.

it is but it doesent work i think i had this problem the first time i got fps unlocker and i think i turned off antivirus and it worked but now even turning antivirus off doesent work.And yes i havea  64 bit system

**Comment by Ewanophobia** [comment]
https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.3.0 Try upgrading, you may of got the 32 bit version.
