### ISSUE TITLE
Error hell

### ISSUE THREAD

**Issue by VotedBlox** [axstin/rbxfpsunlocker#191]
The same error keeps coming up and lags roblox.

**Comment by robloxgamer1025** [comment]
wbu? is the new update not working with the unlocker?

**Comment by Hexcede** [comment]
What specific error are you receiving? Is the error from Roblox? Is the error from FPS unlocker? By "lags" do you mean FPS-wise or network-wise? It's hard to know what your issue is if you don't explain it. If it's the error which says the program is out of date, it's probably out of date.

**Comment by axstin** [comment]
Closed. Please be descriptive. If the problem still occurs with version 4.2.0, reply here again.
