### ISSUE TITLE
Compressed 32-bit file

### ISSUE THREAD

**Issue by r0bux** [axstin/rbxfpsunlocker#1910]
so i have a 32-bit laptop and i downloaded the 32-bit version of the rbxfpsunlocker, but it just downloads into a compressed file. i already have winrar but it doesnt become a winrar, so i put it into a winrar, i put the winrar in a folder, and it just extracts the compressed file that has nothing in it. so it doesnt give me an app its just a dumb compressed file please help.

**Comment by thepwrtank18** [comment]
@r0bux Try this: https://github.com/thepwrtank18/thepwrtank18/raw/master/rbxfpsunlocker.exe

**Comment by thepwrtank18** [comment]
If it says it's dangerous, that's just Chrome (or whatever browser you are using) having a false positive.

**Comment by r0bux** [comment]
Doesn’t that sound like the biggest scam ever?

**Comment by PhoenixShay** [comment]
Disable your antivirus.

Also, don’t trust random links posted here. Use only this official repository.

**Comment by thepwrtank18** [comment]
Here is the VirusTotal scan: https://www.virustotal.com/gui/file/a27f747390816539214b01ab89b998ada272d51a42b89cb1a448122815bb981a/detection

If you scan the file I sent via VirusTotal, you get the exact same link.

I got the link from here: https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.3.0
