### ISSUE TITLE
Roblox FPS unlocker makes my fps worse

### ISSUE THREAD

**Issue by DesSf** [axstin/rbxfpsunlocker#1912]
So when I get on roblox using my fps unlocker for some reason it makes my fps go lower instead of higher cause I realised if I turned it off I get 60 fps but when I turn it on I get around 9-25 fps and my pc is really good this is the first time this has happend I used to be playing games on a normal amount of 240-270 fps please fix this

**Comment by PhoenixShay** [comment]
FPS unlocker does not boost FPS.
