### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by GalaxySlayer399** [axstin/rbxfpsunlocker#1916]
So It worked once i think my computer restarted and then the icon disappeared again and went to the default windows windows media player icon again and then whenever i tried to open it, it said Windows Media Player cannot play the file. The Player might not support the file type or might not support the codec that was used to compress the file. this damn issue keeps coming again and again i can't play some certain games with this fps unlocker please fix this ;-;

**Comment by axstin** [comment]
The download on Github is a zip file; use Windows or software like 7-zip to extract it to a folder and then run the .exe
