### ISSUE TITLE
Virus/Malware Found In Rbxfpsunlocker And errors

### ISSUE THREAD

**Issue by Veeok** [axstin/rbxfpsunlocker#1927]
If you check the new version of Fps unlocker and scan it in all Ant-virus it shows that there is a virus found in, Also new version keeps crashing, When you added the new feature Unlock Player Avast Anti-Virus it will block it don't be lazy and say just disable it, Fix the problem, I'm using the older version Before the new one came and it is much much better.

**Comment by ShaneIsFlawless** [comment]
So which version did you download?

**Comment by PhoenixShay** [comment]
Disable your antivirus.
