### ISSUE TITLE
Roblox Crash.

### ISSUE THREAD

**Issue by USMCLivesOn** [axstin/rbxfpsunlocker#1929]
When I installed this it was working great. I exited the game and I tried to go to a different game and I got "The service is unavailable." I don't know what to do. My Roblox was working fine before I installed this.
![https___www roblox com_home - Google Chrome 12_30_2020 8_06_46 PM](https://user-images.githubusercontent.com/76797453/103389118-ee85bc80-4ada-11eb-9ce7-3a4f5e5d6ac3.png)

**Comment by InternalBrosOfficial** [comment]
Try uninstalling it and then installing it again.

**Comment by axstin** [comment]
Not an RFU issue
