### ISSUE TITLE
Not working on studio (No more higer than 45)

### ISSUE THREAD

**Issue by ConfedMajor** [axstin/rbxfpsunlocker#1937]
So, im testing the program out and i enabled it for the studio, but when i check the summary, it goes, at maximum 45 fps (with lowest QualityLevel).

With higest quality level, it doesn't goes more than 20

![imagen](https://user-images.githubusercontent.com/71795983/103595829-393c7580-4edb-11eb-8be6-c3d1a8bd8c90.png)

My Pc Specs:

![Pc_Specs](https://user-images.githubusercontent.com/71795983/103595945-7c96e400-4edb-11eb-85b0-4681ac277416.png)

**Comment by midmm1** [comment]
Fps unlocker only boosts your fps when your at 60 fps if your not hitting 60 fps it means your pc doesnt support 60 fps for roblox studio

**Comment by axstin** [comment]
Your computer is not powerful enough. See FAQ
