### ISSUE TITLE
Not 240 Fps when i use 240 fps cap

### ISSUE THREAD

**Issue by Skarz111** [axstin/rbxfpsunlocker#1943]
When i toggle 240 fps cap, its not solid and its only around 145 fps.

**Comment by VanExceptGithub** [comment]
it is because your computer does not have the power to run the game at that high. just because the limit is set to 240 doesn't mean it will alway be that speed. example: roblox's defult fps cap is 60 but if your computer does not have the memory or rendering power to run at 60 it wont.

**Comment by VanExceptGithub** [comment]
I dont know fully but that about how it works. Someone can explain it better than me!
