### ISSUE TITLE
I wanted more

### ISSUE THREAD

**Issue by lopumol** [axstin/rbxfpsunlocker#1945]
FPS is kind of slow bc I've done it on tablet

**Comment by kyekiller** [comment]
This just removes your V-Sync from roblox to unlock to your computers FPS. This does NOT boost your performance.

**Comment by lopumol** [comment]
Sad I can try and kill the lag so I need to find another way to remove but I've done it on computer and lag

**Comment by lopumol** [comment]
And also there's a web that can boost my performance?
