### ISSUE TITLE
RFU Completely Ineffective

### ISSUE THREAD

**Issue by ABadNameSniper** [axstin/rbxfpsunlocker#1955]
The latest version of RFU has no effect on my Roblox Player Client. I expect to be able to see 144fps on my monitor of the same Hz, but it's stuck at 60. Changing the FPS cap to 30 also yields no results: it's still stuck at 60. It's been like this for the past 6 or so days, so I would appreciate any help. I can give any additional information as needed.

**Comment by 462ndEnderDude** [comment]
yes it made my fps run at 0 fps

**Comment by LewisTehMinerz** [comment]
Seems to be an issue isolated to a few individuals where the unlocker just doesn't work -- any errors printed out in the console?

**Comment by ABadNameSniper** [comment]
> Seems to be an issue isolated to a few individuals where the unlocker just doesn't work -- any errors printed out in the console?

None at all! It gives the standard "Checking for updates... minimizing to system tray" but nothing happens. I can click on it in the taskbar and "change" the settings, but nothing happens! I've tried reinstalling it, and it doesn't work. Microsoft Windows 10 Pro N, version 10.0.18363.

**Comment by LewisTehMinerz** [comment]
Seems that way.. I can't replicate it at all.

One last thing I would ask you to do, try switching from 64-bit to 32-bit and vice versa and see if it makes a difference. Roblox's clients are 32-bit so maybe 64-bit just doesn't work in some cases.

**Comment by ABadNameSniper** [comment]
![image](https://user-images.githubusercontent.com/77552588/105719140-92e6fd00-5ee7-11eb-8228-c3636598eb9e.png)
Attached Processes: 0? That sounds like a problem. It would make sense, considering RFU can't even cap it at 30...

**Comment by LewisTehMinerz** [comment]
That means it can't even find the game.

**Comment by ABadNameSniper** [comment]
Now what? Do I learn C++ and debug it myself?

**Comment by LewisTehMinerz** [comment]
At this point, that is unironically a great idea, but I know it's completely impractical.

We have no debugging information to help with this, I guess I could quickly write up a debug release for you to try and get some logging output for you but it's a shot in the dark. Oh well, let's give it a go. Give me ~10 minutes.

**Comment by LewisTehMinerz** [comment]
Here is a quick debug build that's designed to just log everything relating to the process management stuff.
[rbxfpsunlocker.zip](https://github.com/axstin/rbxfpsunlocker/files/5867638/rbxfpsunlocker.zip)
Run this, and then try running the game. Send a screenshot of the logs when you can. If you are getting 
```
obtaining process snapshot
NOK
```
then it's not relating to how RFU gets processes.

**Comment by LewisTehMinerz** [comment]
&lt;self-promotion>
I wrote an [FPS unlocker check](https://www.roblox.com/games/5885482504/FPS-Unlocker-Check) game as well which you may find useful. Just a simple game to tell you if it works correctly.
&lt;/self-promotion>

**Comment by ABadNameSniper** [comment]
That's a start! 
![image](https://user-images.githubusercontent.com/77552588/105732420-0859ca00-5ef6-11eb-8ce5-b295f8dbf992.png)

**Comment by LewisTehMinerz** [comment]
Oh boy, this issue! I had this in my fork of RFU. Let me go fix it...

**Comment by LewisTehMinerz** [comment]
[rbxfpsunlocker.zip](https://github.com/axstin/rbxfpsunlocker/files/5867859/rbxfpsunlocker.zip)

**Comment by ABadNameSniper** [comment]
Same system error.

**Comment by LewisTehMinerz** [comment]
![image](https://user-images.githubusercontent.com/8019327/105733412-7075d380-5f29-11eb-95bb-71d3821f83f5.png)
One last try: [rbxfpsunlocker.zip](https://github.com/axstin/rbxfpsunlocker/files/5867885/rbxfpsunlocker.zip)

**Comment by ABadNameSniper** [comment]
I think it's telling me something... perhaps that it's... **OK**?
![image](https://user-images.githubusercontent.com/77552588/105734182-fbd67100-5ef7-11eb-91df-08a306d45249.png)

**Comment by LewisTehMinerz** [comment]
Okay, what that tells me is that it can find the game client (which is good!) but it can't open the process handle (which is bad!).

This is actually implying that the Roblox client is running as administrator whilst RFU isn't. Can you try restarting RFU as administrator, then post your logs here?

**Comment by ABadNameSniper** [comment]
Heyo!
![image](https://user-images.githubusercontent.com/77552588/105735084-eca3f300-5ef8-11eb-9dd0-5f6ff374409b.png)
Oh how I miss the buttery smoothness of high refresh rate gaming on Roblox!
Thank you so much for your help! I strive to be the friendly internet stranger as you are, I just need some skills to be more helpful!

**Comment by LewisTehMinerz** [comment]
Glad to be of service! Feel free to delete my debugging build and use the regular client again. 😄
