### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by OverFHGL** [axstin/rbxfpsunlocker#1958]
Does not unlock my FPS

**Comment by jayIen** [comment]
Are you using the Microsoft Store version or the one downloaded off the website? RFU really only works on the website app, not the Microsoft app.

**Comment by LewisTehMinerz** [comment]
Please try running RFU as administrator (#1955 dupe?).

**Comment by ppcenter** [comment]
i ran it as administrator and nothing happened its still doesn't work my fps used to be at 210 now its goes to 75-130 when i cap it at 240

**Comment by LewisTehMinerz** [comment]
@ppcenter That means the FPS unlocker is working fine. You are constrained by your hardware.

> I say with great emphasis, as this seems to be a common misconception, that Roblox FPS Unlocker is an FPS *unlocker* and **not a *booster***. It will not boost Roblox's performance in any way and only removes Roblox's 60 FPS limit.
