### ISSUE TITLE
my fps is stuck on 30 or 40 and i lag very hard but i already open my fps unlocker

### ISSUE THREAD

**Issue by reee31** [axstin/rbxfpsunlocker#196]

**Comment by lr-hextar** [comment]
if you have a nvidia graphics card you can disable v-sync on roblox to allow your fps over 60 (still use the fps unlocker)
First open roblox, then close it.
Right click on your desktop background and hit nvidia control panel
Next, press adjust image settings with preview and at the bottom, select use the advanced 3d image settings
On the side menu, press manage 3d settings, then scroll all the way down and turn "vertical sync" to "OFF" 
Hit apply
70+ FPS :)

**Comment by axstin** [comment]
[I used this unlocker and my framerate is the same or below 60. Why?](https://github.com/axstin/rbxfpsunlocker#FAQ)
