### ISSUE TITLE
VR capping FPS to 75

### ISSUE THREAD

**Issue by jackbearguy** [axstin/rbxfpsunlocker#1960]
after using Roblox in VR and then going back on to my pc and switching VR mode to off im capped at VR's limit of 75fps in roblox and fps unlocker just stopped working can someone help??

**Comment by axstin** [comment]
How are you "switching VR mode to off"? Does restarting RFU or your PC fix the problem?

**Comment by jackbearguy** [comment]
@axstin I'm not too technically so i don't know what an RFU is but to turn VR mode off I just deleted Roblox file directory completely on my C Drive, and re installed Roblox. But don't worry today I launched Fps Unlocker and Roblox and I was running 240 frames on Arsenal again. Anyway Thanks for replying :)
