### ISSUE TITLE
IN GAME cap lock at 60

### ISSUE THREAD

**Issue by FuryPL** [axstin/rbxfpsunlocker#1977]
Hello!
I have problem with my cap lock, i tried to reinstall roblox, rbx, 64x, 32x and more more, but everytime it weren't help.
Ok, so 
In game i have 60 fps lock, i alt tab, or click anything that is not game, my fps goes into 170 fps+, when i go back to game, fps instantly goes into to 60 fps
In game: 60 fps
In game (**alt tabbed**): 170+ fps
In console i have that **i must wait for patch it.**

I tried to cap lock at **140** fps, **120** fps, **75** fps, **240** fps.
I can't unlock my fps while i am in game (when i am not in, rbx works good).

**Comment by axstin** [comment]
See: https://github.com/axstin/rbxfpsunlocker/issues/1883
