### ISSUE TITLE
⚠Trojan Virus Alert⚠

### ISSUE THREAD

**Issue by LexiaDevRoblox** [axstin/rbxfpsunlocker#1988]
⚠Trojan Virus Alert⚠   READ NOW
⚠WARNING⚠: THIS HAS A VERY BAD VIRUS. DO NOT DOWNLOAD.
DO NOT DOWNLOAD
DOWNLOAD 4.1.1 INSTEAD
Link to 4.1.1: https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.1.1
THIS VERSION IS SAFER

**Comment by LexiaDevRoblox** [comment]
> ⚠Trojan Virus Alert⚠
> ⚠WARNING⚠: THIS HAS A VERY BAD VIRUS. DO NOT DOWNLOAD.
> DO NOT DOWNLOAD
> DOWNLOAD 4.1.1 INSTEAD
> Link to 4.1.1: https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.1.1
> THIS VERSION IS SAFER

**Comment by PhoenixShay** [comment]
shut
