### ISSUE TITLE
error

### ISSUE THREAD

**Issue by katist** [axstin/rbxfpsunlocker#1994]
it said [ERROR] Variable scan failed! This is probably due to a Roblox update-- watch the github for any patches or a fix here: 
![Screenshot 2021-02-16 123920](https://user-images.githubusercontent.com/78238725/108100690-427d3e00-7054-11eb-9f3f-07084aaa8f65.jpg) What should I do.

**Comment by PhoenixShay** [comment]
please download the latest version and disable your antivirus
