### ISSUE TITLE
I tab into roblox after openining the fps unlocker and it drops down to 60 and tab out it goes back up. I redownloaded and disabled my antivirus but it works sometimes.

### ISSUE THREAD

**Issue by WheezyTheWaffle** [axstin/rbxfpsunlocker#200]

**Comment by WheezyTheWaffle** [comment]
I tab into roblox after openining the fps unlocker and it drops down to 60 and tab out it goes back up. I redownloaded and disabled my antivirus but it works sometimes. Ive tested multiple games but for somereason it wont work 80% of the time

**Comment by axstin** [comment]
Does this happen if you fullscreen? (try both F11 and Alt+Enter)
Also, what graphics card are you running?

**Comment by WheezyTheWaffle** [comment]
I use a 1080 and I did try full screening and in full screening still won’t work

**Comment by WheezyTheWaffle** [comment]
just updated to the new version and now it works thanks.
