### ISSUE TITLE
New update Today, Doesnt unlock my fps

### ISSUE THREAD

**Issue by FulszArh** [axstin/rbxfpsunlocker#202]
My fps was 100+ anytime i run the FPSUNLOCKER, until today update, when i updated it to the new version, its staying on 60 and wont go above 60

**Comment by Mudock-Yatho** [comment]
Take a picture of the FPS unlocker console when you run the updated FPS unlocker with Roblox.
(Right click the picture for FPS unlocker -> Toggle Console)
![image](https://user-images.githubusercontent.com/24907394/74480517-acc63600-4e76-11ea-88a9-065bd2082d08.png)

The only private information it might show would be your account's username on your computer, you can blur that out if you want.

**Comment by FulszArh** [comment]
Yeah i went to toggle console and its like this 
https://gyazo.com/4105bd6f661ce6f5dbe0c350a5177e04

**Comment by FulszArh** [comment]
![image](https://user-images.githubusercontent.com/61029998/74481561-ddc05e00-4eaa-11ea-9618-034bfa0f594f.png)

**Comment by FulszArh** [comment]
Yeah i clicked Toggle Console and its like this
![image](https://user-images.githubusercontent.com/61029998/74481611-f4ff4b80-4eaa-11ea-98bf-babe6bd262fa.png)

**Comment by FulszArh** [comment]
Oh it works now, i restarted the PC, sorry !
