### ISSUE TITLE
fps unlocker closes / crashes roblox & closes itself

### ISSUE THREAD

**Issue by cookiefy** [axstin/rbxfpsunlocker#203]
a few seconds after launching the .exe, roblox crashes itself & the application closes itself
though this issue can be stopped by opening the console, i'd still like to know why it does this

**Comment by axstin** [comment]
What version of Windows are you on and do you use an Anti-Virus? Also, try navigating to `%localappdata%\CrashDumps` in your file explorer and let me know if there are any rbxfpsunlocker dump (.dmp) files.

**Comment by cookiefy** [comment]
i'm on windows 10 & there is nothing in %localappdata%\CrashDumps, I use AVG Antivirus free & i've tried whitelisting it in my files

**Comment by Mudock-Yatho** [comment]
What version of Windows 10. (Windows key + R, type `winver`).
What type of Windows 10. (Home, Professional, Insiders or Enterprise.)

Try making a gif of running rbxfpsunlocker and having the console open when trying to use it with Roblox. (Go to the rbxfpsunlocker symbol at the bottom and right clicking it to "toggle console")
