### ISSUE TITLE
says it cant find variable it crashes itself

### ISSUE THREAD

**Issue by Encursive** [axstin/rbxfpsunlocker#206]
pls help asap thx
![Select Roblox FPS Unlocker 4 2 0 (64-bit) Console 16_02_2020 19_19_27](https://user-images.githubusercontent.com/61124160/74612472-9d0c5300-50fd-11ea-8f24-398769156056.png)

**Comment by PhoenixShay** [comment]
please try the latest release https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.2.0
