### ISSUE TITLE
Variable scan failed?

### ISSUE THREAD

**Issue by Dafffffy** [axstin/rbxfpsunlocker#207]
Please fix this it's really annoying
![b77788f45e314bcdc053bf8f32fc83b3](https://user-images.githubusercontent.com/61125888/74613897-db5c3f00-510a-11ea-8cd1-30cc3794d21c.png)

**Comment by NoahHere** [comment]
> Please fix this it's really annoying
> ![b77788f45e314bcdc053bf8f32fc83b3](https://user-images.githubusercontent.com/61125888/74613897-db5c3f00-510a-11ea-8cd1-30cc3794d21c.png)

Same thing happens to me!
I have the 4.2.0 Version so this shouldn't pop up right?

**Comment by PhoenixShay** [comment]
re-download the latest release (https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.2.0) and try again
