### ISSUE TITLE
my fps unblocker would not work 

### ISSUE THREAD

**Issue by PolarBaeJr** [axstin/rbxfpsunlocker#209]
it used to work with 240 fps or higher but now when i launch it it does not work i have a ryzen 5 3600 cpu and a rtx 2060 gpu pls fix

**Comment by Destroyer5678i** [comment]
run it as administrator to see if it fixed it

**Comment by PhoenixShay** [comment]
try the latest release https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.2.0
