### ISSUE TITLE
Virus/Crashing Game

### ISSUE THREAD

**Issue by Ajspyman** [axstin/rbxfpsunlocker#214]
it keeps saying the app has a virus and crashes my game when i try to play

**Comment by axstin** [comment]
Which AV do you use?

**Comment by Ajspyman** [comment]
I use the free av

**Comment by JALJR-sudo** [comment]
avg is unreliable use malwarebytes if you are tech savy use windows defender with common sense

**Comment by PhoenixShay** [comment]
disable the antivirus or make an exception
