### ISSUE TITLE
Rbxfpsunlocker crashes Roblox and deletes itself afterwards.

### ISSUE THREAD

**Issue by Tepa06** [axstin/rbxfpsunlocker#215]
Rbxfpsunlocker has a slight problem.
When I open roblox and try to play a game with rbxfpsunlocker, the game crashes and rbxfpsunlocker deletes itself.

**Comment by axstin** [comment]
What Anti-Virus do you use? Does the issue still occur if you disable it or add an exception?

**Comment by supremely454** [comment]
wait do you need an anti virus for this?

**Comment by supremely454** [comment]
i got AVG and turned off everything so it doesent delete it but it still delets it afterwards.
And a massege says that after closing the application its gonna compress something this has been my problem for months i started when the 4.0 came out!

**Comment by PhoenixShay** [comment]
turn off the antivirus or make an exception
