### ISSUE TITLE
Virus Detect a virus called IDP.Generic

### ISSUE THREAD

**Issue by Loccury** [axstin/rbxfpsunlocker#216]
When i open rbxfpsunlocker 4.20, my anti-virus detect a virus called idp.generic and i don't know what happened i only know that roblox crash and my anti-virus eliminated my rbxfpsunlocker

**Comment by Gamer929** [comment]
well, i got:
[Trojan:Win32/Occamy.C](https://github.com/axstin/rbxfpsunlocker/issues/205)

**Comment by axstin** [comment]
See [FAQ](https://github.com/axstin/rbxfpsunlocker#FAQ)
