### ISSUE TITLE
Full screen issue

### ISSUE THREAD

**Issue by Mantegaloka** [axstin/rbxfpsunlocker#220]
When I am using rbx fps unlocker, and I f11 to full screen, my game freezes until f11 to get out of full screen again. 
My resolution is 1080p and 144hz frame rate
(before roblox updated on Wednesday

**Comment by Mantegaloka** [comment]
My resolution is 1080p and 144hz frame rate

**Comment by ImPanda123** [comment]
depends on your os and gpu drivers

**Comment by Mantegaloka** [comment]
> depends on your os and gpu drivers

Sorry, i dont get it

**Comment by ImPanda123** [comment]
try to update your GPU Drivers

**Comment by ImPanda123** [comment]
this might help

**Comment by Mantegaloka** [comment]
> this might help

thank you, it helped!
