### ISSUE TITLE
FPS unlocker stuck in "checking for updates"

### ISSUE THREAD

**Issue by hewwoworld124** [axstin/rbxfpsunlocker#221]
For some reason, the command didn't close and it's not in my taskbar thingy when u press the arrow.

**Comment by 666fufu** [comment]
happened to me too i just deleted it and downloaded the new version

**Comment by iimoomoo** [comment]
how do I delete it?

**Comment by longsawk0102** [comment]
go to downloads and place it in the trash can
or you can right click and press "cut"

**Comment by iimoomoo** [comment]
i can't uninstall it, it's stuck

**Comment by PhoenixShay** [comment]
download a new version from the releases https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.2.0
