### ISSUE TITLE
Open rbxfpsunlocker turn on roblox and program and roblox crashes

### ISSUE THREAD

**Issue by etain06** [axstin/rbxfpsunlocker#222]
Hi, today i had a problem with the program i can open it but when i open the roblox it crashes, if you are intrested what kind of an antivirus i am using it is AVG antivirus. Thank you for your respond.

**Comment by Mantegaloka** [comment]
It might be because of the update roblox got today

**Comment by PhoenixShay** [comment]
disable the antivirus or make an exception
