### ISSUE TITLE
Please help me!!!

### ISSUE THREAD

**Issue by Mariusz232323** [axstin/rbxfpsunlocker#224]
When i use this program my GPU have BIG TEMPERATURE AND LOAD I've had this problem since Thursday so what is going on

**Comment by ImPanda123** [comment]
just dont use the program xD i mean its a fps unlocker ofc that is going to put more load on your gpu what do you expect to happen it removes the fps cap placed by the devs so the game can use more resources to push more frames

**Comment by Mariusz232323** [comment]
ehh now i have 40 temp and STILL gets crash maybe bad cooling but idk cpu temp is 50 so lol ?
just don't know  why i have this problem

**Comment by PhoenixShay** [comment]
fps unlocker makes your computer work harder to render more frames
