### ISSUE TITLE
Ping spikes when using the FPS unlocker.

### ISSUE THREAD

**Issue by TheBananaBoi** [axstin/rbxfpsunlocker#226]
As the title says. For some games I play, like Counter blox and others, the ping is good, but while using for some games, like flood escape 2, it spikes all the way to 1000 ping. Not sure why it's like that, but it's been bugging me. Don't seem to see a solution to this, so might as well make this issue.

**Comment by TheBananaBoi** [comment]
My gameplay is definitely affected, since can spike 1000 ping, it can take either half a second, or 3 seconds for the game to register I pressed a button on FE2. Not sure why it's like that. There are many games I have issues with, but FE2 is the easiest to explain with.

**Comment by TableFlipGod** [comment]
Sucks to be you, this isnt fps unlocker related your internet sucks

**Comment by TheBananaBoi** [comment]
Table, I literally get 30-90 depending on servers. It's just that on some games, using the FPS unlocker boosts the ping up to 1000. Never had 1000 ping with my Wi-Fi. I always get low ping, and I mean low ping.

**Comment by Ostrichboy** [comment]
i also get the same thing too when i use the fps unlocker

**Comment by PhoenixShay** [comment]
post a video of you playing without FPS Unlocker and then another while using it so we can verify it's FPS Unlocker causing the problem
