### ISSUE TITLE
RBXunlocker just recently started destroying my frames

### ISSUE THREAD

**Issue by brodaaan** [axstin/rbxfpsunlocker#23]
https://gyazo.com/fadae1f4f6b45a8e3f4d5e14dc43500e

i was getting 300 in the past, not sure what may have caused it

sidenote: it kills my frames on every storage device

**Comment by xXAggressorXx** [comment]
i think im only like that but not only me so how to fix that? wait for update?!

**Comment by brodaaan** [comment]
reinstalling windows works... i think the owner gave up on this thing though, considering 15 days later no reply. on most every other issue he replies very quickly

**Comment by xXAggressorXx** [comment]
Thx for u reply btw u destroy frame too? after reset windows u work?

Pada tanggal 11 Nov 2018 16:56, "brodaaan" <notifications@github.com>
menulis:

**Comment by brodaaan** [comment]
i was fine after i reinstalled windows
