### ISSUE TITLE
I only get 240 fps

### ISSUE THREAD

**Issue by Guest47123** [axstin/rbxfpsunlocker#230]
I am on a steady 240 fps and I am sure that my PC can get more frames then that , but I won't get one frame more.

**Comment by tableflipgod69** [comment]
Do you even have a monitor thats 240hz if not doesnt matter.

**Comment by daniel11420** [comment]
Hey! You might accidentally be on a 240 FPS cap. You should right click the RBX FPS Unlocker in your system tray, go to FPS cap and see if it's on 240. If it is, you can set it to none to get more FPS.
