### ISSUE TITLE
[ERROR] that i don't know how to fix

### ISSUE THREAD

**Issue by zypherrrr** [axstin/rbxfpsunlocker#233]
[ERROR] Variable scan failed! This is probably due to a Roblox update-- watch the github for any patches or a fix.  and i don't get it, i have the latest version of the unlocker but it still says it.

**Comment by PhoenixShay** [comment]
download latest release from https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.2.0 and try both 64bit / 32bit
