### ISSUE TITLE
Something About This App He Moving In The Virus Chest For No Reason On Avast While Using rbxfpsunlocker

### ISSUE THREAD

**Issue by DarkBenjamin19** [axstin/rbxfpsunlocker#235]
Can SomeOne Fix This same thing needs a update to fix this asap

**Comment by AliAkbar3253** [comment]
I think it uses scripting and has an API so just disable it from the control panel for 10 minutes, then launch the unlocker and open Roblox and then you can enable protections once again

I use Avast myself and do this all the time,

**Comment by PhoenixShay** [comment]
disable your antivirus or make an exception
