### ISSUE TITLE
WinRAR cant execute the file.

### ISSUE THREAD

**Issue by mrkoppei** [axstin/rbxfpsunlocker#238]
When i opened the file for the first time, i opened Roblox, then opened the file. Then an error popped up, saying that WinRAR failed to execute it. I extracted the file, opened it and it would not work. I searched Google for info and for possible fixes and even tried to use the troubleshooter but to no avail. Its possible that the file is corrupted, or incompatible to my operating system.

**Comment by Uranite** [comment]
are you an idiot? extract it.

**Comment by PhoenixShay** [comment]
disable your antivirus or make an exception, if that doesnt fix it, redownload the file
