### ISSUE TITLE
FPS Gets to 3 or 2 after a few minutes

### ISSUE THREAD

**Issue by AliAkbar3253** [axstin/rbxfpsunlocker#243]
Running perfectly on the latest version. When I join Jailbreak or Counter Blox (or basically any other game) I can play perfectly for like 10-20 minutes or so then my game starts to go dip on 45 FPS then down and down and it literally goes to 2 FPS after some time

**Comment by Corsaka** [comment]
Does this happen without the FPS unlocker?

**Comment by PhoenixShay** [comment]
check task manager, it shouldn't be fps unlocker
