### ISSUE TITLE
RobloxFPSUnlocker Doesn't work in vr

### ISSUE THREAD

**Issue by DoggoSlayz** [axstin/rbxfpsunlocker#244]
As title reads.  Could this be added?

**Comment by TableFlipGod** [comment]
Roblox in fucking vr..

**Comment by reee31** [comment]
fpsunlocker is not compatible with roblox vr

**Comment by Azorexs** [comment]
Well is it gonna be added?

**Comment by Azorexs** [comment]
That sounds like impatient but e

**Comment by Corsaka** [comment]
Can VR headsets even support 60+ fps?

**Comment by PhoenixShay** [comment]
@Corsaka VR headsets usually run at 90hz, higher end ones like the index can go even higher (144)

you don't need fpsunlocker for roblox vr - roblox uncaps it to 90fps on their own
