### ISSUE TITLE
My fps unlocker is not working on intel celeron j1900

### ISSUE THREAD

**Issue by reee31** [axstin/rbxfpsunlocker#248]
My fps is not applying whenever i use the fps unlocker and im using intel celeron j1900 on intel

**Comment by TableFlipGod** [comment]
OMG WHY, YOUR CPU IS SO OLD AND YOU DONT NEED IT BECAUSE THIS NEEDS A 75+
REFRESH RATE MONITOR...

**Comment by reee31** [comment]
this is just a present about 6 years ago or 4 we really have money but we use it at y school beacuse im graduating man.Why you scream

**Comment by KC1KAD** [comment]
@reee31 
It says right in the FAQs that you need a computer powerful enough to see any benefit from using this.
You just confirmed in your previous comment that your computer is 4-6 years old with a Celeron processor. Celeron processors are trash. Please read the FAQs before posting a bug report. I have quoted the FAQ #3 below for your reference. Jesus.

> I used this unlocker and my framerate is the same or below 60. Why?
I say with great emphasis, as this seems to be a common misconception, that Roblox FPS Unlocker is an FPS unlocker and not a booster. It will not boost Roblox's performance in any way and only removes Roblox's 60 FPS limit. To take advantage of RFU, **a computer powerful enough to run Roblox at _more than 60 FPS_ is required**. This being said, if you know your computer is powerful enough but still aren't seeing higher framerates with the unlocker, feel free to submit an issue.

**Comment by jared704** [comment]
> @reee31
> It says right in the FAQs that you need a computer powerful enough to see any benefit from using this.
> You just confirmed in your previous comment that your computer is 4-6 years old with a Celeron processor. Celeron processors are trash. Please read the FAQs before posting a bug report. I have quoted the FAQ below for your reference. Jesus.
> 
> > I used this unlocker and my framerate is the same or below 60. Why?
> > I say with great emphasis, as this seems to be a common misconception, that Roblox FPS Unlocker is an FPS unlocker and not a booster. It will not boost Roblox's performance in any way and only removes Roblox's 60 FPS limit. To take advantage of RFU, **a computer powerful enough to run Roblox at _more than 60 FPS_ is required**. This being said, if you know your computer is powerful enough but still aren't seeing higher framerates with the unlocker, feel free to submit an issue.

@KC1KAD They're trash but they're still super fun to play with. I have like 4 celerons in my tech bin and they all bring something weird to the table, ha.

**Comment by reee31** [comment]
@jared704 this is the type of  guy that i want to be friends with

**Comment by reee31** [comment]
@KC1KAD Hey if your reading this i the meaning i was supposed to say is were saving money beacuse im graduating and the celeron i just pick  that type of proccesor beacuse im just a kid back then ok you really need to under stand someone first

**Comment by reee31** [comment]
@KC1KAD Even though there trash there still playable and not every people have a the money to buy a stronger gpu and plus you just dint under stand what i mean so read the comment above this.

**Comment by PhoenixShay** [comment]
unfortunately your cpu is fairly old, it probably just cannot get above 60fps. fps unlocker only removes the cap, it does not "boost" your fps
