### ISSUE TITLE
This is still a bug Variable scan failed! This is probably due to a Roblox update-- watch the github for any patches or a fix. i hate it!

### ISSUE THREAD

**Issue by BuildermanMarch** [axstin/rbxfpsunlocker#256]
it really annoyng i wannt to play arsenal i can't even get 10 kills with this lag pls fix it!

**Comment by TableFlipGod** [comment]
You dont need this fps unlocker. It only works for monitors above 60 hz

**Comment by Muf7in2** [comment]
I also got the same error

**Comment by PhoenixShay** [comment]
try both 64 bit and 32 bit version on the latest release
