### ISSUE TITLE
Would this program trigger a VAC ban?

### ISSUE THREAD

**Issue by g1gabyt3333** [axstin/rbxfpsunlocker#257]
I usually close this program when I'm not playing Roblox but yesterday I forgot to close it. I logged on to a vac secured server with the program enabled. I know it doesn't use a dll injector anymore but I do not want to risk getting a ban.

**Comment by AmbassadorLaZer** [comment]
I don't think it will, but if it was a dll injector still, you probably would've been VAC banned.

**Comment by Teedie** [comment]
of course not

**Comment by TableFlipGod** [comment]
Vac isnt part of roblox retard

**Comment by LewisTehMinerz** [comment]
@TableFlipGod Chill dude.

VAC *shouldn't* ban you, but there have been reports of it falsebanning people simply by leaving certain applications it detects as cheats open. For example, there was a person who got VAC banned by having Cheat Engine run in the background whilst playing CS:GO. Not attaching it to CS:GO, just leaving it running. If you get banned, send in a ticket to Valve and explain the situation, however it's very rare that VAC will falseban.

**Comment by axstin** [comment]
RFU doesn't touch any processes except for Roblox. You should be fine.
