### ISSUE TITLE
Error: Variable scan failed

### ISSUE THREAD

**Issue by HaveFUNRICH** [axstin/rbxfpsunlocker#259]
[ERROR] Variable scan failed! This is probably due to a Roblox update-- watch the github for any patches or a fix.

**Comment by KamuFlasje** [comment]
[ERROR] Variable scan failed! This is probably due to a Roblox update-- watch the github for any patches or a fix.- how do I fix this?

**Comment by PhoenixShay** [comment]
try both 64 bit and 32 bit version on the latest release
