### ISSUE TITLE
Ping Spike

### ISSUE THREAD

**Issue by Tropicaline** [axstin/rbxfpsunlocker#260]
When I joined royale high for the egg hunt my ping was around 100-50k when I closed out of the fps unlocker it went back to around 60

**Comment by Corsaka** [comment]
Issue with the game using a specific call which relies on player FPS to get its responses.

It gets overloaded by non-standard FPS values.

**Comment by axstin** [comment]
See https://github.com/axstin/rbxfpsunlocker/issues/275
