### ISSUE TITLE
Mac when

### ISSUE THREAD

**Issue by TheHaunte123** [axstin/rbxfpsunlocker#262]
Because it's really annoying when it's only on windows instead of mac ;/

**Comment by AmbassadorLaZer** [comment]
As it says in the description "No. Roblox FPS Unlocker was written only for the Windows platform and I currently have no plans to change this. However, those more experienced and with Mac hardware are free to port this project to Mac", He won't make it for Mac, but if someone is more experienced at making programs on Mac are free to port this project.
