### ISSUE TITLE
Bad FPS even when running software

### ISSUE THREAD

**Issue by Archaiz** [axstin/rbxfpsunlocker#263]
So I recently downloaded the 64 bit version for Strucid, and when I am on full screen I only have 45 FPS average, that has random spikes every few seconds. I cant download 32 bit version because I cannot open it, as it says "Cannot complete Extraction" This is driving me CRAZY!!! PLEASE HELP

**Comment by XxEB** [comment]
Same my FPs is sometimes 45 but then it goes back down to 30
It basically stays between 30 to 45 when im just trying to get rlly high FPS to play games like Strucid and MM2

**Comment by LewisTehMinerz** [comment]
> 3. **I used this unlocker and my framerate is the same or below 60. Why?**
>
> I say with great emphasis, as this seems to be a common misconception, that Roblox FPS Unlocker is an FPS *unlocker* and not a *booster*. It will not boost Roblox's performance in any way and only removes Roblox's 60 FPS limit. To take advantage of RFU, a computer powerful enough to run Roblox at more than 60 FPS is required.

**Comment by TableFlipGod** [comment]
It means your pc sucks, get a better one
