### ISSUE TITLE
Fps Unlocker Not Unlocking Fps

### ISSUE THREAD

**Issue by Galaxey** [axstin/rbxfpsunlocker#264]
So i recently downlaoded this sofware and noticed it would not unlock the fps plz help me

**Comment by OutRite** [comment]
What is your FPS before and after running the program?

**Comment by SophieIsSupreme** [comment]
I had the same problem.

**Comment by TableFlipGod** [comment]
It does work, your pc may not be able to handle this game

**Comment by PhoenixShay** [comment]
run the file
make sure the cap is set to above 60
if it doesn't work, your computer isn't powerful enough or you have vsync enabled
