### ISSUE TITLE
Unlocker does not attach to process

### ISSUE THREAD

**Issue by iSuuuuuck** [axstin/rbxfpsunlocker#265]
So recently the fps unlocker sometimes doesn't attach to the process. I'd say about 70-80% of the time it does not. I tried reinstalling both Roblox and the unlocker but it still would have this issue. The issue is with all the games I play on Roblox. It used to work just fine but recently at has become like this.

**Comment by killercloudj** [comment]
Its cause of the new roblox updates u just have to wait until he updates the FPS unlocker

**Comment by Teedie** [comment]
it works fine for me though ;P

> Its cause of the new roblox updates u just have to wait until he updates the FPS unlocker

**Comment by PhoenixShay** [comment]
record a video if you're still having this issue please
