### ISSUE TITLE
Has error

### ISSUE THREAD

**Issue by DHJDDHHD** [axstin/rbxfpsunlocker#267]
The variable cannot be scanned so I think you need to update it

**Comment by TableFlipGod** [comment]
I think you need to shut up and wait

**Comment by Corsaka** [comment]
> I think you need to shut up and wait

Don't be a dickhead.

> The variable cannot be scanned

Could you provide more detail, such as a screenshot of the console?

**Comment by PhoenixShay** [comment]
try both 64 bit and 32 bit from https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.2.0 again
