### ISSUE TITLE
how to fix roblox fps unlocker failed to connect to github

### ISSUE THREAD

**Issue by Parzival1224** [axstin/rbxfpsunlocker#268]

**Comment by TheWhiteX** [comment]
how to fix it?

**Comment by TheWhiteX** [comment]
i cant use the roblox fps unlocker because failed to connect to github

**Comment by TheWhiteX** [comment]
please help me

**Comment by PhoenixShay** [comment]
download latest version from https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.2.0
