### ISSUE TITLE
How to disable FPS unlocker?

### ISSUE THREAD

**Issue by DatGhostt** [axstin/rbxfpsunlocker#272]
How do you disable FPS unlocker? I want to disable it because there are too many FPS pings and it makes the game unplayable.

**Comment by LewisTehMinerz** [comment]
Either set the FPS cap to 60 or exit the application.

**Comment by axstin** [comment]
See [this issue](https://github.com/axstin/rbxfpsunlocker/issues/275) if you're having network problems using RFU.

RFU can be "disabled" by clicking the RFU icon in the system tray and pressing `Exit`.
