### ISSUE TITLE
RBXfpsunlocker causes massive ping spikes almost constantly.

### ISSUE THREAD

**Issue by MrSlazz** [axstin/rbxfpsunlocker#274]
Although having a high fps is wonderful, Roblox is simply unplayable at times when my ping suddenly jumps into the thousands. (For reference, without it, I average 30-100 ping), and if this doesn't get fixed, it's not really worth using.

**Comment by TableFlipGod** [comment]
Its your internet, works fine for me

**Comment by Corsaka** [comment]
Which specific games is this occuring on? It seems like certain code in certain games relies on player FPS for something or other, so it'd be good to get them so we can make a list of problem games.

**Comment by axstin** [comment]
Created a centralized issue for this problem: https://github.com/axstin/rbxfpsunlocker/issues/275
Please leave a reply here!
