### ISSUE TITLE
Virustotal.com and window defender think fps unlock 32 bit is dangerous and is a virus

### ISSUE THREAD

**Issue by Aimerick1234** [axstin/rbxfpsunlocker#276]
I tried to download fps unlocked 4.20 and it told me it is dangerous. Fps unlocker 4.11 can still be open without any problems but I would prefer to get the newer version to be able to use it in studio. There are currently 34 engines detected the file (from what virus total is telling me). I hope you will be able to do something

**Comment by PhoenixShay** [comment]
@axstin can leave his paypal if you're interested in paying the $400 to buy a code signing certificate, otherwise not much he can do
