### ISSUE TITLE
Uninstalls by it's self?

### ISSUE THREAD

**Issue by windowscj2** [axstin/rbxfpsunlocker#278]
One day, I was playing aresenal when RBX fps unlocker dissapearred. I tried relaunching it but it said "Windows is looking for [insert file name here]" And I was like, what just happened?

**Comment by axstin** [comment]
It is likely your Anti-virus software is deleting the unlocker. Please see the [FAQ](https://github.com/axstin/rbxfpsunlocker#FAQ)

**Comment by windowscj2** [comment]
It’s not, as it would have told me there’s a vorus.

**Comment by TableFlipGod** [comment]
No, it’s your anti virus

**Comment by axstin** [comment]
Files do not delete themselves. If you disable your anti-virus does the issue still occur?

**Comment by windowscj2** [comment]
Yes, it does. Just downloaded it with the anti virus off, (including windows defender) and still dispersal.

**Comment by TableFlipGod** [comment]
No it doesn’t chief, works fine for me

**Comment by windowscj2** [comment]
it removed again- I even turned off my anti-viruses. Including real time
protection windows defender, and avast.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by PhoenixShay** [comment]
you must have another antivirus because fps unlocker does not delete itself.

**Comment by TableFlipGod** [comment]
Your pc is just shit mate

**Comment by windowscj2** [comment]
I have removed avast, and turned off windows defender. now what. You'll
expect me to say it removed again? yes it did.
(DUN DUN DUN DUN)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by axstin** [comment]
Hi, I'm not sure what the problem is but I can assure you RFU has no code or functionality to remove itself. Where is `rbxfpsunlocker.exe` located on your PC before it gets deleted?

**Comment by Razuatix** [comment]
@axstin umm poop poop pee pee haha :3c

**Comment by windowscj2** [comment]
It isn’t located on my desktop. The 1st time I use it, it’s fine. The
second time, it disappears.

**Comment by windowscj2** [comment]
Not isn’t, it*
