### ISSUE TITLE
It stopped working again

### ISSUE THREAD

**Issue by alii981** [axstin/rbxfpsunlocker#28]
Now it crashes the game if you start the program after roblox,and it doesn't even work anymore,atleast the fps unlock,idk about vsync

**Comment by alii981** [comment]
EDIT
It just crashes the game,had a weird setting that locked the fps,sorry

**Comment by alii981** [comment]
It works now,idk what was causing it

**Comment by How-Bout-No** [comment]
You should close this issue then ;)
