### ISSUE TITLE
How Do I Actually Use It

### ISSUE THREAD

**Issue by Utuber4life5** [axstin/rbxfpsunlocker#280]
So I have it but it does not do anything to Roblox. Any other installments I am required to have?

**Comment by axstin** [comment]
What is your FPS before and after using the unlocker (use Shift+F5 in game)

**Comment by ineedtoknowhowtousefpsunlocker** [comment]
my fps before using it is 30 and i don't know how to like use it it works some times

**Comment by axstin** [comment]
RFU is an unlocker, not a booster. Your computer is not powerful enough to use this program @ineedtoknowhowtousefpsunlocker 
Please read [this](https://github.com/axstin/rbxfpsunlocker#FAQ)

**Comment by ultimatemoocow12** [comment]
MINE GOES UP TO 500 FPS OMG :D

**Comment by Utuber4life5** [comment]
My FPS is usually 50 and doesnt change

**Comment by PhoenixShay** [comment]
FPS unlocker can’t boost your FPS, you are restricted by how good your computer is.
