### ISSUE TITLE
Blue Screen And Pc Crashes

### ISSUE THREAD

**Issue by ZTGGaming** [axstin/rbxfpsunlocker#29]
I have experienced many full system crashes and a blue screen my guess is program instability one common crash is when you leave the game i fixed this my ending the roblox task every time but i have experienced other crashes since sadly ive lost trust in the program and will be waiting for a Update to fix it.

**Comment by PhoenixShay** [comment]
not reproducible, if you have any further info open a new issue with the bsod errors and if possible the dump files
