### ISSUE TITLE
FPS unlocker not working

### ISSUE THREAD

**Issue by derferdude** [axstin/rbxfpsunlocker#290]
So, I've tried running the FPS unlocker on roblox but It hasn't worked. I've tried fullscreen and have still gotten nothing. Can someone explain to me what is happening?
![evidence of fps unlocker not working](https://user-images.githubusercontent.com/65195489/81612106-4768df00-93aa-11ea-9423-6d09fc378f79.PNG)

**Comment by derferdude** [comment]
Is there something I'm doing wrong or does it have to do with my computer settings?

**Comment by derferdude** [comment]
I'm well aware that my computer can run roblox at 60 fps but when I'm at full graphics it drops instantly

**Comment by Httpbrxck** [comment]
The fps unlocker isnt working for me too, my fps will only go to 60 fps, I have a fast pc that runs roblox at 200. So it isn't my pc.

**Comment by Httpbrxck** [comment]
I found a fix, Just delete it and re download it.

**Comment by REZHub396** [comment]
If your computer is unable to achieve more than 60 fps at full graphics, the fps unlocker will do nothing.

**Comment by ArnavSnow** [comment]
Same thing happening to me and i did everything correct

**Comment by ArnavSnow** [comment]
dame my graphics also drop instantly

**Comment by axstin** [comment]
See FAQ: your PC doesn't seem powerful enough to take advantage of RFU.
