### ISSUE TITLE
Keeps disappearing/deleting

### ISSUE THREAD

**Issue by SwavyChris** [axstin/rbxfpsunlocker#293]
I don't know what the fuck is going on with this download. It worked the first time I ever used it then deleted off my PC. I have all my windows defender programs turned off and it still does this. It's starting to piss me off because you have people saying it's doing this and your acting like your app is perfect and not coming up with a solution. Get your shit together and please help.

**Comment by PhoenixShay** [comment]
Disable all the antivirus installed on your computer. Otherwise, feel free to build it yourself, the source code is right here.
