### ISSUE TITLE
FPS Unlocker version 4.2.0 wont work!

### ISSUE THREAD

**Issue by ArnavSnow** [axstin/rbxfpsunlocker#294]
When I installed it I put it to 240 FPS then when I checked my FPS it was at 31 please fix this!!!

**Comment by PhoenixShay** [comment]
FPSUnlocker cannot boost your FPS. You are limited by how good your computer is.

**Comment by ArnavSnow** [comment]
How un-modifie my open/clode section

**Comment by ArnavSnow** [comment]
Please help me make it work my computer always so laggy :C
