### ISSUE TITLE
didn't work when my dad spent 5 dollars the fucking fps unlocker wasn't on my pc 

### ISSUE THREAD

**Issue by bruhmowbruh** [axstin/rbxfpsunlocker#305]
pls help me with this

**Comment by agariomaster10** [comment]
the FPS unlocker doesn't cost money, be careful buying random things.

**Comment by PhoenixShay** [comment]
FPS unlocker is free
https://github.com/axstin/rbxfpsunlocker/releases

**Comment by bruhmowbruh** [comment]
i bought the money won
