### ISSUE TITLE
fps glitch

### ISSUE THREAD

**Issue by RealUnivers123** [axstin/rbxfpsunlocker#31]
when you rename the rbxfpsunlocker - legacy to rbxfpsunlocker.exe it will keep going open cmds 32 bit thing and it got my cpu to 98 geeez , guys dont do this
another thing is that it the program does not work

**Comment by axstin** [comment]
Do not rename rbxfpsunlocker-legacy.bat to rbxfpsunlocker.exe. It's a batch file, not an executable file. I assume you did this because rbxfpsunlocker.exe was missing (probably due to your anti-virus software deleting it). See FAQ: https://github.com/axstin/rbxfpsunlocker#faq
