### ISSUE TITLE
FPS Unlocker no longer works on Studio

### ISSUE THREAD

**Issue by Mudock-Yatho** [axstin/rbxfpsunlocker#34]
Studio is now 64-bit when possible (Whether CPU/machine supports it.), this isn't cross compatible with x86  player, needs to have separate portions for both, as well as, detection for when studio isn't 64-bit and also support for player 64-bit when it comes out. (Preparing for it now is better than waiting.)
![image](https://user-images.githubusercontent.com/24907394/53674102-40482c00-3c51-11e9-844f-74535c7f1670.png)

**Comment by axstin** [comment]
Fixed-- see v4.0
