### ISSUE TITLE
Leaving this in the background when playing fortnite = ban

### ISSUE THREAD

**Issue by v1tal** [axstin/rbxfpsunlocker#37]
got fucking owned today lads and lost my main fortnite account cus i was stupid enough to forget to exit this, probably an obvious issue to most but just letting everyone know

**Comment by 3dsboy08** [comment]
This is due to EasyAntiCheat scanning for blackbone signatures in all processes then bans if they are present - this also happened with my legitimate™ software™.

**Comment by Slappy826** [comment]
Well Darn

**Comment by axstin** [comment]
This should no longer be an issue! Sorry about your account.
https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.0
