### ISSUE TITLE
Could cause bans via DLL injection check

### ISSUE THREAD

**Issue by 3dsboy08** [axstin/rbxfpsunlocker#4]
doesn't bypass roblox's new DLL injection check, could lead to bans.

**Comment by xetrics** [comment]
yeah fix it idiot

**Comment by Slappy826** [comment]
fix or riot

**Comment by Rerumu** [comment]
riot

**Comment by yeahidontknow** [comment]
https://www.reddit.com/r/PhantomForces/comments/8t3skm/i_was_banned_for_using_the_fps_unlocker/

RIP this person; the fps unlocker does indeed need the bypass

**Comment by 3dsboy08** [comment]
I did make a version that _**should**_ bypass the new checks, but its not guaranteed. I did have to protect it though so people cant RE on how I bypass it.

[rbxfpsunlocker-prot.zip](https://github.com/axstin/rbxfpsunlocker/files/2130036/rbxfpsunlocker-prot.zip)

Password is "rbxfpsunlocker".

**Comment by axstin** [comment]
Fixed: https://github.com/axstin/rbxfpsunlocker/commit/700ece69d17a9d47f6a359be9e2f7d1293ca09d2

For the time being, this bypasses Roblox's DLL detection/logging. Hopefully they won't go out of their way to patch it (unlikely, but you never know).
