### ISSUE TITLE
Chrome Blocks The File????

### ISSUE THREAD

**Issue by retsamegodGH** [axstin/rbxfpsunlocker#42]
I try downloading the latest version, 3.1, but Google Chrome does not let me. There is no button to "open up anyway", only to learn more about why it is a "malicious file".
 [image](https://user-images.githubusercontent.com/44173202/56084773-ec278e80-5e2f-11e9-9d02-687cfea97de4.png)
Let me know if you find a fix or this gets fixed in a new update. Tell me if you reply by contacting me on Discord, as I don't really check this site much.
Dr. DM#4547 is my tag. Thanks!

**Comment by axstin** [comment]
Should no longer be an issue in the latest release! https://github.com/axstin/rbxfpsunlocker/releases
If the problem persists, disable "Safe Browsing" under Chrome Settings->Advanced->Privacy and security
