### ISSUE TITLE
Significant FPS drop after updating to 4.0

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [axstin/rbxfpsunlocker#43]
Using i5-8400 + RTX 2060, still under 60fps
Setting: Previously 144fps cap VSync at 3.1, now only 144fps cap, lag

**Comment by axstin** [comment]
What is your FPS before attaching? After attaching, what does your FPS look like (use Shift+F5) for different caps (75, 144, & None) and how do these numbers compare with v3.1?

**Comment by SandwichDev** [comment]
I'm also getting fps drops from 75 all the way down to 40 at times.

**Comment by Pythonic-Rainbow** [comment]
![image](https://user-images.githubusercontent.com/25037295/56181006-47c76700-603e-11e9-9b3d-e4d3c0132b87.png)
An example with no cap, its not utilising the resources it had

**Comment by axstin** [comment]
I get around 80fps average in that game with the cap set to none in both v3.1 and v4.0. Could you test in an empty (baseplate) place and also check if the numbers seen with Shift+F5 in-game match your RTSS overlay?

Thanks

**Comment by Pythonic-Rainbow** [comment]
In that case you might have a GPU bottleneck. But at my place, u can see my 3.1 screenshot able to reach 142fps vsync, which means my system does have the capabilities to achieve this framerate. But in 4.0 it isn't promising. I would say looking at baseplate is kinda meaningless as 4.0 does work, just not as powerful as 3.1. In baseplate the game is simply rendering a single rectangular object, so both 3.1 and 4.0 should achieve 140-144fps. Anyways I will try when I am free
