### ISSUE TITLE
dont gain fps from 4.0

### ISSUE THREAD

**Issue by sskadff** [axstin/rbxfpsunlocker#44]
my fps stays the same and doesnt change at all when i use fps unlocker

**Comment by axstin** [comment]
What is your FPS before using the unlocker? Remember RFU only removes the FPS limit of 60, it doesn't boost your FPS.

**Comment by PrismonZ** [comment]
It says 'Fails to connect' right after I run the unlocker. Could you please help me with this issue?

**Comment by PrismonZ** [comment]
Also, I use a 32 bit.

**Comment by axstin** [comment]
@PrismonZ please open a new issue: https://github.com/axstin/rbxfpsunlocker/issues/new
(also make sure you are using the latest version)

**Comment by PrismonZ** [comment]
Alright. Thanks!

**Comment by KeysandLemons** [comment]
Yes. I have the same issue as PrismonZ
