### ISSUE TITLE
Being unable to gain fps from the latest version whilst using a 32bit (windows 7)

### ISSUE THREAD

**Issue by PrismonZ** [axstin/rbxfpsunlocker#46]
I'm unable to believe fps and Idk if it's because of the version of windows I'm using or that it's rigged.

**Comment by PrismonZ** [comment]
![image](https://user-images.githubusercontent.com/48875234/56553303-5b8c4380-65d1-11e9-9b21-aa293a618a6f.png)

**Comment by PrismonZ** [comment]
![image](https://user-images.githubusercontent.com/48875234/56553321-6941c900-65d1-11e9-8729-bc10f7d5d79b.png)

**Comment by Celected** [comment]
Probably because you don't hit the 60FPS mark. You need a powerful enough PC to achieve lots of FPS...

**Comment by axstin** [comment]
RFU is a FPS unlocker, not a booster. See issue: https://github.com/axstin/rbxfpsunlocker/issues/7

**Comment by KeysandLemons** [comment]
What version should you use for this issue?
