### ISSUE TITLE
Virus Protection AVG

### ISSUE THREAD

**Issue by Celected** [axstin/rbxfpsunlocker#47]
So... While I was playing roblox and using the FPS Unlocker for Strucid.. Roblox Closed out and this came up
![image](https://user-images.githubusercontent.com/49899077/56687169-b3937a80-66a3-11e9-9ae0-30d0a0d2cc37.png)

**Comment by sezongithub** [comment]
Redownload it and exclude it from protection also

>FPS bullshit

**Comment by axstin** [comment]
With version 4.0, the number of anti-virus false positives should have decreased significantly. However, [some still exist](https://www.virustotal.com/#/file/f40f3bf2ca61ab5bbb9940137d457be1c0f5177df8ff8f7377e7f363a3de75db/detection). Try adding RFU to your AV's exceptions and see the FAQ: https://github.com/axstin/rbxfpsunlocker#FAQ
