### ISSUE TITLE
Failed to connect to github / Variable scan failed

### ISSUE THREAD

**Issue by Kazokox** [axstin/rbxfpsunlocker#48]

**Comment by Kazokox** [comment]
I need help pls! D:

**Comment by Kazokox** [comment]
IT says that when I open the file D: before/after ingame

**Comment by KeysandLemons** [comment]
I need help as well. this is my other issue as well idk how to fix this

**Comment by Kazokox** [comment]
All I had to do was just click ok and then you check your fps it goes to 60+
To check your Fps press Shift+F5 and you will see your fps
