### ISSUE TITLE
Make fpsunlocker for MAC!!! 

### ISSUE THREAD

**Issue by Rektovsky** [axstin/rbxfpsunlocker#49]
I believe you will gain a lot  more recognition if u do one for mac as well, since there are multiple users who suffer from fps rates that mac provides. We can run more than 100 fps but with your help of course.

**Comment by axstin** [comment]
I currently do not have a Mac to test on nor have I ever developed software for MacOS. RFU relies heavily on Windows API; setting up a Mac dev environment and porting the project is a task I don't have time (or motivation) for. Closing this issue for now.

**Comment by NakralMijal** [comment]
you do know about virtualboxes right? if you dont know, let me explain. It creates like another pc inside another pc, you can edit the OS in the virtualboxes. You can use this to develop that. Please make it on Mac, its unfair for mac users like me are suffering on low fps. "the ants on the shore are visible, but the elephants on the reeds are not".

**Comment by theLMGN** [comment]
> you do know about virtualboxes right? if you dont know, let me explain. It creates like another pc inside another pc, you can edit the OS in the virtualboxes. 

Many of the times, VM's (not virtualboxes, virtualbox is the name of a piece of software that lets you run VMs) don't support full 3D acceleration, and have keyboard and mouse input issues. VirtualBox on macOS doesn't even support audio.

> You can use this to develop that

No you can't.

> Please make it on Mac, its unfair for mac users like me are suffering on low fps.

This won't raise your FPS if you're already below 60, the only thing that can do that is by lowering graphics settings, or getting a new mac (or using an eGPU)

I understand your fustration. I want a FPS unlocker for macOS, so I can use my fancy 144hz monitor without rebooting my computer into Windows, but macOS and Windows are very different and it's not as simple as you might think it would be.

**Comment by NotAarav** [comment]
sigh i wish us mac users had a reliable fps unlocker
