### ISSUE TITLE
No injector.exe

### ISSUE THREAD

**Issue by teammmmm34** [axstin/rbxfpsunlocker#5]
I downloaded every files but there is no injector.exe plz help

**Comment by TRHalil2** [comment]
ye thats sucks

**Comment by axstin** [comment]
Make sure you're downloading from releases:
https://github.com/axstin/rbxfpsunlocker/releases 

![Download](https://i.imgur.com/0S2K0D4.png)

If there's still no `injector.exe` after unzipping `rbxfpsunlocker.zip` it is most likely your anti-virus software removing it. Add an exception for the files if this is the case.
