### ISSUE TITLE
Error : You need a x64 Base Processor // I have already have a x64 PC.

### ISSUE THREAD

**Issue by virtual088** [axstin/rbxfpsunlocker#55]
I've recently downloaded your FPS unlocker and I've been having this problem and I don't know how to fix it. I have a x64 PC but it keeps saying I need the x64 version even though I have it already, It's in the title. Please help me

**Comment by axstin** [comment]
Can you post your console output (Menu->Toggle Console)?

Thanks

**Comment by virtual088** [comment]
![Screenshot (80)_LI](https://user-images.githubusercontent.com/50601374/57662909-85b89c00-75a6-11e9-91b0-6d8de6b97187.jpg)

**Comment by axstin** [comment]
Old issue; should be resolved in the latest versions of RFU.
