### ISSUE TITLE
MAC Support 

### ISSUE THREAD

**Issue by Rektovsky** [axstin/rbxfpsunlocker#56]
Axstin, Maybe you can try and develop one for mac and ask payment for it? I am willing to pay as well as, others who have mac

**Comment by restrxnings** [comment]
Has Anyone found out yet how to get it on Mac, I’ve thought of a wine bottler

**Comment by swole1522** [comment]
I've tried wine bottler with this, but it hasn't worked.

**Comment by Rektovsky** [comment]
We need to find out how it works...

**Comment by Rektovsky** [comment]
Did anyone find out?

**Comment by Rektovsky** [comment]
Ive tried other programs that supports .exe file but none of them worked rip... Help Axstin!

**Comment by axstin** [comment]
https://github.com/axstin/rbxfpsunlocker/issues/49
