### ISSUE TITLE
Error while loading a game after starting unlocker

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [axstin/rbxfpsunlocker#59]
![image](https://user-images.githubusercontent.com/25037295/58370746-a1c02400-7f3c-11e9-8ac9-f680b21b98f2.png)

**Comment by axstin** [comment]
[Version 4.1](https://github.com/axstin/rbxfpsunlocker/releases) tries to fix this problem by retrying upon failure. Let me know if this is still an issue.
