### ISSUE TITLE
Virustotal 

### ISSUE THREAD

**Issue by venompog** [axstin/rbxfpsunlocker#63]
https://www.virustotal.com/gui/file/f40f3bf2ca61ab5bbb9940137d457be1c0f5177df8ff8f7377e7f363a3de75db/detection

SentinelOne (Static ML) -DFI - Suspicious PE
Webroot -W32.Trojan.Gen

Why are all of the av's fine, yet these 2 seem to think its a trojan?

**Comment by ThatCoderBoss13** [comment]
it's just a false positive those happen with most exe's like this

**Comment by axstin** [comment]
As ThatCoder mentioned, these are false positives. This is actually a huge improvement to [older versions of rbxfpsunlocker](https://www.virustotal.com/gui/file/dc8534235b8df148f811bd1b861b5dffa292a3f8fa577a121353d0526a80d07d/detection). If you don't feel comfortable using the release binaries users are always free to compile the project themselves.
