### ISSUE TITLE
FPS Locked At 60

### ISSUE THREAD

**Issue by KillSwitchNext** [axstin/rbxfpsunlocker#64]
Even after I downloaded the FPS Unlocker and did all the steps I still get 60 FPS, I even right clicked the FPS Unlocker it and made sure that the FPS Limit was none.

**Comment by Johnyknowhow** [comment]
Yeah, seems to be a recent issue that's affecting lots of people. Doesn't seem to lock onto the RobloxPlayerBeta process at all, even when you launch it after or before Roblox. Attached processes stays at 0, and the console doesn't show any errors or much of anything.

**Comment by KillSwitchNext** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/51799389/59620825-d36f7980-90fb-11e9-8d56-b45f6fbb9e28.png)
Just a quick picture to show you what I mean.

**Comment by axstin** [comment]
The "Render" metric is what's important. In your screenshot, it's almost at 200 which means the unlocker is working.
