### ISSUE TITLE
Roblox Freezes after a few minutes.

### ISSUE THREAD

**Issue by oDissGod** [axstin/rbxfpsunlocker#66]
Roblox freezes but I can still hear my character move around or if I shoot.

**Comment by KillSwitchNext** [comment]
That happens in some games for some reason.

**Comment by CelestiusBlitz** [comment]
@oDissGod Does this issue happen consistently while only using the program?

Does this issue still occur? If not, please close this thread.

**Comment by axstin** [comment]
This is likely due to the game's anti-cheat. Contact the game developers for help.
