### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by jahlil2** [axstin/rbxfpsunlocker#67]
its saying fps unlocker is running but in would press shift and f5 and it wont work

**Comment by Bluezxe** [comment]
what do you mean by shit and f5

**Comment by KillSwitchNext** [comment]
shift + f5 is how you check your fps in game.

**Comment by sky454561** [comment]
why roblox

**Comment by CelestiusBlitz** [comment]
@jahlil2 Could you please describe the environment that you are running the program in? Could you elaborate and describe any possible causes?
