### ISSUE TITLE
New roblox update breaks it.

### ISSUE THREAD

**Issue by aLphabeaT1** [axstin/rbxfpsunlocker#69]
Hello, since the roblox "logo change" it seems my fps unlocker is no longer working and it displays the following message: 
![image](https://user-images.githubusercontent.com/31017190/60391491-d8ea9d80-9ac5-11e9-9c12-a2dee4b60c62.png)

**Comment by KillSwitchNext** [comment]
Try uninstalling and reinstalling, the fps unlocker is working fine for me even after updating.
