### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by kozaart** [axstin/rbxfpsunlocker#75]
![image](https://user-images.githubusercontent.com/53393936/62003978-c4a9b880-b0e4-11e9-9c30-e42209561b93.png)

**Comment by mxdanger** [comment]
Not like it would make a difference considering you're only getting 40fps.

**Comment by kozaart** [comment]
What do you mean im using this to get better fps duh. lmao

**Comment by kozaart** [comment]
What are you trying to say isnt the website to make your fps better.

**Comment by mxdanger** [comment]
All it does is remove the 60fps cap.

**Comment by axstin** [comment]
Please see FAQ: RFU does not boost your performance.

If you are no longer experiencing the error shown in your screenshot with the latest version of RFU, please close this issue.

Thanks
