### ISSUE TITLE
It's Working!

### ISSUE THREAD

**Issue by Linerly** [axstin/rbxfpsunlocker#76]
Well, this thing is working for me! I've seen a bit of change from the FPS unlocker. 

Roblox is running around 70-80 fps on the lowest Graphics level, while 40 fps on the maximum Graphics level (I need to close some programs to have the results). 

If you want to see the FPS, just press `Shift` + `F5`.

**Comment by CelestiusBlitz** [comment]
This is not an issue. Please close this issue. @Linerly
