### ISSUE TITLE
4.0 didn't get detected as anything, but 4.1 did

### ISSUE THREAD

**Issue by lennnnyy** [axstin/rbxfpsunlocker#77]
If I try to download 4.1 windows defender detects it as a Trojan:Win32/Conteban.B!ml
Now, as much as I would like to think it is a false-positive, I am not sure if I can trust it. Can anyone out there vouch for me please?
VirusTotal detection: https://www.virustotal.com/gui/file/4a35c3ad79428447c208c1f6837ff46b440d0121b2f3bae748950f20db17c6ff/detection

**Comment by axstin** [comment]
Not sure why more anti-viruses are flagging this version over 4.0:
https://www.virustotal.com/gui/file/afa2caea9f01710c4a265cd68768d42a697f5dd4174e69fddf7f8ccf1659469e/detection (4.1 32-bit)
https://www.virustotal.com/gui/file/ddc7a2c8c3361aaef8378e7dfa571b1a4b64452792986b1c43d49c2fcd91990b/detection (4.1 64-bit)

Anyway, these are false-positives that will (hopefully) disappear over time. Difference in source code between 4.0 and 4.1 can be seen here: https://github.com/axstin/rbxfpsunlocker/commit/5f0419a05fa466de8db5032bba704b3cbc9d1a29

If you don't trust it, the project can be compiled from source with Visual Studio 2017/2019.
