### ISSUE TITLE
ROBLOX Crash

### ISSUE THREAD

**Issue by Bvxing** [axstin/rbxfpsunlocker#79]
Whenever i'm in a game using fps unlocker 5-10 minutes later the game randomly freezes for a few minutes then crashes.

**Comment by axstin** [comment]
I'm unable to reproduce this issue. Does this occur in any game, every time?

**Comment by supremely454** [comment]
for me it says that it will be compresd in some way

**Comment by supremely454** [comment]
and it happens every time

**Comment by PhoenixShay** [comment]
if you're still having this issue please record a video or give repro instructions
