### ISSUE TITLE
Suggestion?  Don't seem to be using your contact info you provided.

### ISSUE THREAD

**Issue by Pokl1** [axstin/rbxfpsunlocker#8]
Have an option for the injector to be in Notification Center that way you don't have to always open it for each ROBLOX game you join.

**Comment by axstin** [comment]
Sorry about the Discord contact. I can't use the account anymore and forgot to update the readme. Anyways, good suggestion-- I'll try working on it today.

**Comment by axstin** [comment]
Added in 2.0:
https://github.com/axstin/rbxfpsunlocker/releases/tag/v2.0
