### ISSUE TITLE
FPS Unlocker 4.1 does not work, nor do the previous versions for me all the sudden?

### ISSUE THREAD

**Issue by davygunshot** [axstin/rbxfpsunlocker#80]
After I've received and installed the updated version (4.1), the FPS unlocker all the sudden has stopped working. I went back and installed the previous versions and that also did not work. My FPS is still locked onto 60 and does not exceed beyond that point. I do not know what the issue is, but I believe it has something to do with either ROBLOX or perhaps the coding (Also I've tried closing the FPS unlocker via Task Manager, but the issue is still present). I can guarantee that my PC can handle this as it is running on a i5 7600k w/ GTX 1060. Any support would be great.  

Thanks!
-dav

**Comment by axstin** [comment]
Hi dav, could you save your console output when this happens (RFU->Toggle Console) and share it here? You can censor any names in file paths.

**Comment by sw123klw2000** [comment]
> Hi dav, could you save your console output when this happens (RFU->Toggle Console) and share it here? You can censor any names in file paths.

Watch thread started
Injecting into new process 0000000000000568 (pid 408)
ProcUtil::GetModuleInfo: buffer = C:\Users\sebwy\AppData\Local\Roblox\Versions\version-63d5cf76777d4db4\RobloxPlayerBeta.exe
ProcUtil::FindModuleInfo: path = C:\Users\sebwy\AppData\Local\Roblox\Versions\version-63d5cf76777d4db4\RobloxPlayerBeta.exe
ProcUtil::FindModuleInfo: info.path = C:\Users\sebwy\AppData\Local\Roblox\Versions\version-63d5cf76777d4db4\RobloxPlayerBeta.exe
[0000000000000568] Process Base: 0000000000A60000
[0000000000000568] GetTaskScheduler: 0000000000BDB090
New size: 1
[0000000000000568] Scheduler: 0000000006B21590
[0000000000000568] Frame Delay Offset: 544
Purging dead process 0000000000000568 (pid 408) (code 0)
New size: 0

**Comment by axstin** [comment]
Closing due to age and inactivity. If you still have problems with the latest version of RFU, [open a new issue.](https://github.com/axstin/rbxfpsunlocker/#submitting-an-issue)
