### ISSUE TITLE
How Do I Uninstall?

### ISSUE THREAD

**Issue by SoloSnxper** [axstin/rbxfpsunlocker#81]
So, I've tried to uninstall because i need this on a completely different device and I just wanted to know whether this works or not, but i can't seem to find any way to uninstall and I don't want to put my rbx account in any risk at all. Hope there's a solution.

**Comment by axstin** [comment]
Simply delete `rbxfpsunlocker.exe` and its `settings` file.

**Comment by SoloSnxper** [comment]
When I go to delete is says "The action can't be completed because the file is open in rbxfpsunlocker"

**Comment by axstin** [comment]
Make sure the unlocker isn't running (click RFU->Exit, end the process in Task Manager, or restart your computer) before deleting the files.

**Comment by SoloSnxper** [comment]
Thanks, restarted my computer just in case and all the sudden they deleted. Thank you!
