### ISSUE TITLE
Repository is not licensed (LICENSE file missing)

### ISSUE THREAD

**Issue by ddavness** [axstin/rbxfpsunlocker#82]
This means that technically you are giving nobody the permission to modify/study the source code, redistribute modified versions, etc.

You might want to take a look at https://choosealicense.com and pick one that best suits your needs.

**Comment by mxdanger** [comment]
Pull request #96 has a LICENSE file.

**Comment by axstin** [comment]
Added in commit https://github.com/axstin/rbxfpsunlocker/commit/ef4270548e88a8502c5d5a95e58fb4cc60d84123
