### ISSUE TITLE
Failed To Connect

### ISSUE THREAD

**Issue by StrucidTryhard** [axstin/rbxfpsunlocker#83]
Failed To Connect

**Comment by StrucidTryhard** [comment]
I think this is only me but when i download fps unlocker it just says Failed to connect to GitHub when i open it

**Comment by dricoslayer** [comment]
mee to ;-;

**Comment by axstin** [comment]
See issue: https://github.com/axstin/rbxfpsunlocker/issues/62

>This error means RFU couldn't connect to GitHub to check for updates. This could be because you are not connected to the internet, GitHub is down, or your firewall is blocking RFU.
>
>The error can be safely ignored (press OK) and the unlocker will still function, although you will need to manually check for updates.
