### ISSUE TITLE
Help with capping and uncapping!

### ISSUE THREAD

**Issue by lukewae** [axstin/rbxfpsunlocker#85]
So I used to use this without any problems but I recently updated windows and installed 4.1 (not sure which one is causing the problem, but I am pretty sure it is the windows update) and when I use the unlocker when i click out of roblox my fps is uncapped but when i click back in to roblox about 2 seconds later it caps. This doesn't happen when I initially boot the program but after a while it starts occuring. this happens in windowed and fullscreen mode. I love the product and dont want it to be ruined by windows auto updating, thanks!

**Comment by lukewae** [comment]
I also have two monitors, one at 144hz and one at 60hz, but this has never caused problems prior, so it would be weird to only affect me now.

**Comment by ddavness** [comment]
Likely unrelated, see #84

**Comment by axstin** [comment]
When you select Roblox's window, does your FPS begin decreasing immediately or after 2 seconds? Does this happen on your 144hz monitor or only the 60hz? Does fullscreening using Alt+Enter on either monitor fix the issue?

Thanks.

**Comment by axstin** [comment]
Moving #84 here:

>trevorselso31: my fps stays locked at 60 when i am playing. it does go up when i am on another window so say i have chrome open on top of the roblox window you can see that the fps goes up to around 250 but as soon as you click on the roblox window to play it goes right back to 60 fps

**Comment by lukewae** [comment]
It's almost immediately after I click in to roblox, sorry for the really late reply, It started working again after a restart but then stopped working again. The last thing i opened was steam and discord, could any of these cause it?

**Comment by PhoenixShay** [comment]
some sort of windows performance enhancement, or roblox throttling itself
