### ISSUE TITLE
FPS Unlocker causes intense frame dropping at random times.

### ISSUE THREAD

**Issue by thewallbro2a** [axstin/rbxfpsunlocker#86]
I just installed the unlocker on version 4.1, and it works great. I have one singular issue where at random times I will experience intense frame dropping (such as FPS falling below 30 at least visually) and I can't fix it until I wait for the lag to end. It's not an issue with my computer, as when I press Shift F5, the FPS counter is on 75 FPS, the framerate I capped it on.
To recap, I see intense frame dropping at random times which are out of my control, and changing graphics quality doesn't affect this
The frame dropping goes on for some time and goes back to normal and will come back later
I haven't tested this on any other games than Reason 2 Die Awakening. I will list the game, and my hardware specs below.
Processor: AMD Ryzen 5 2600X
Graphics card: AMD RX 580
Drives: Samsung 970 Evo NVMe PCIe M.2 250GB, WD Blue 2TB
16 GB Ram
Game I had this issue on: https://www.roblox.com/games/177200271/Reason-2-Die-1-3-5a
This issue could be on other games, I just haven't tested this myself.

**Comment by CelestiusBlitz** [comment]
Have you reinstalled the program fully? Do you have any other problematic background programs? (i.e running other games while playing roblox can sometimes lower your FPS dramatically)
