### ISSUE TITLE
Could you be any more vague?

### ISSUE THREAD

**Issue by Denkiluren** [axstin/rbxfpsunlocker#87]
It's just not working, What do open the program with? That's something that should be specified, I opened it with Microsoft Visual Studio because that's the only thing there and yet my fps is still at 60
Not to mention your explanation on how to make it work is outdated, It's an SLN file yet you refer to it as an EXE file.

I-7 6700k
3,222gb's of storage
GTX 1070

**Comment by PhoenixShay** [comment]
https://github.com/axstin/rbxfpsunlocker/releases/tag/v4.1

Click where it says "download here (64 bit)"

**Comment by axstin** [comment]
Please follow [the usage instructions](https://github.com/axstin/rbxfpsunlocker#usage)
