### ISSUE TITLE
When I Alt+Enter in ROBLOX, my FPS is capped at 144.

### ISSUE THREAD

**Issue by m4ttxd** [axstin/rbxfpsunlocker#89]
Why does this happen? I have my FPS Cap set to 240 or None and my FPS Stays at 144.
![image](https://user-images.githubusercontent.com/12838421/63891531-673eab00-c9b3-11e9-9ed8-f19ada5a771c.png)

**Comment by Haxagon** [comment]
Because Vsync Exists.

**Comment by mxdanger** [comment]
That means it's doing its job properly.

**Comment by Haxagon** [comment]
> That means it's doing its job properly.

Not necessarily properly with a 240FPS Cap, but assuming OP is on 144Hz Monitor, it's working absolutely fine
