### ISSUE TITLE
The unlocker makes OBS skip frames

### ISSUE THREAD

**Issue by TominoCZ** [axstin/rbxfpsunlocker#9]
I was streaming ROBLOX yesterday and it kept skipping frames even above 50% when the frame rate is unlocked, making the stream literally run at down to 5 FPS. This also really increased the CPU usage of OBS during that time. It seems to happen only when there's more things on the screen. It does not happen when the frame rate is locked. 

Could this be because of OBS's API hook that just got overloaded because of having around 200FPS in the game? This must be due to the ROBLOX's game loop..

Oh and btw this was happening even when not streaming, just with OBS opened in the background, capturing the game with Game Capture.
I also use SLOBS (Streamlabs OBS).

**Comment by MSWindows95** [comment]
OBS will have problems with it because since Roblox is running with no FPS cap, the GPU will go to 100% usage, leaving no room for OBS to use. OBS uses a little bit of everything, CPU, ram, and GPU.

**Comment by TominoCZ** [comment]
I have a 60Hz monitor. I also have a ryzen 5 1600 and an AMD R9 270x

**Comment by MSWindows95** [comment]
Ok, let me know what FPS you get normally with the frame rate uncapped I may be able to at least give you a workaround.

**Comment by TominoCZ** [comment]
100 to 200, but that really depends on what game you play. I get 400 when looking to the ground.
It would be cool if I could set my own FPS cap using this unlocker. Also if you press Shift + F5 then the network receive speed is the same as the FPS which I'm not sure if is ok.

It's still weird how this is happening.. how f'd does the ROBLOX render engine have to be to do this to OBS :D

Btw the reason I need this unlocker is because without capping it, sometimes the game looks like it's running at 30 FPS, but it's not, according to the microprofiler.
Here's a showcase of my problem with some more info: https://www.youtube.com/watch?v=Ue7o8zsTS3o

If ROBLOX ran ok, the video would be smooth 60 fps with no frame skipping at all.

**Comment by MSWindows95** [comment]
On the video you posted, Roblox to me looked very smooth. You may wanna look at the video again.

**Comment by MSWindows95** [comment]
Oh, now I see sorry, when I looked at it I kind of rushed cause I was doing a few other things at  the time.
My fault on that one.
Since OBS is skipping frames, not just a full frame drop, the only thing I can think of is a possible encoder overload, please if you don't mind to take a look in your OBS settings such as resolution, bitrate, basically the more crucial things for your stream, and post it here.

**Comment by TominoCZ** [comment]
SLOBS doesn't drop or skip any frames in any other game for me.
That 60 FPS thing without this unlocker isn't caused by SLOBS. It does that without recording, that's why I recorded it. It's weird.

**Comment by MSWindows95** [comment]
I am not 100% of this works, it may not be the greatest workaround since you will not get the absolute most FPS, but it will be a bit more than with it capped at 60. But you should install Rivatuner (https://www.guru3d.com/files-get/rtss-rivatuner-statistics-server-download,14.html) which will be able to set an FPS cap, let's say of 100 FPS, which will provide less latency than 60, but may reduce it to save some GPU load for OBS, since that is what I think it could be.

**Comment by MSWindows95** [comment]
Oof. Try raising the cap, what did you cap it to?

**Comment by TominoCZ** [comment]
I capped it to 60, raising the cap didn't help. rablax is broke :/

**Comment by MSWindows95** [comment]
Yeah something is definitely wrong. While playing Roblox and running OBS,
send me a screen of task manager, I can get an idea of what is the issue,
and run it with Roblox COMPLETELY uncapped framerate.

**Comment by MSWindows95** [comment]
Yeah something is definitely wrong. While playing Roblox and running OBS, send me a screen of task manager, I can get an idea of what is the issue, and run it with Roblox COMPLETELY uncapped framerate.

**Comment by TominoCZ** [comment]
Hmm printscreen doesn't seem to work for anymore..

The SLOBS process normally uses 11% of the CPU while streaming/recording.

When I look at some more complex building from more parts, SLOBS skips frames so much that the framerate in SLOBS is down to 30(it can go even lower) while the in-game framerate is actually 150, no matter if streaming/recording or not. 
When I'm streaming/recording during that framerate drop, the CPU usage of SLOBS goes up to 20%(the lower the framerate in SLOBS, the higher the CPU usage).

**I tried recording for this test with this preset:**
4100 bitrate
x264 encoder
veryfast preset
1080p60 unscaled

ROBLOX at max graphics.

**Comment by MSWindows95** [comment]
What is the GPU usage at with OBS and Roblox on?

**Comment by TominoCZ** [comment]
OBS barely uses the GPU. It's around 3% (because of the preview)

Roblox uses the GPU at max since it runs as fast as it can get. at around 98-99%.

Could it be because the graphics card can't handle the preview rendering and the game at the same time?

**Comment by MSWindows95** [comment]
That is why I bet, OBS doesn't have any GPU usage because Roblox is taking
all of it up. I suggest you reduce your framerate cap again, or reduce your
OBS resolution to 900p.

**Comment by TominoCZ** [comment]
With unlocking the framerate and running RivaTuner, the framerate is unstable. Like really unstable.

**Comment by TominoCZ** [comment]
Yeah.. 720p helps a bit. A friend of mine actually had the same problem in COD:BO3. He was getting around 90 FPS and his stream was choppy, just like mine. Both CPU and GPU usage of BO3 were around 80% for him. He enabled VSync and since then, it is buttery smooth. ROBLOX is just broken, let's hope they fix it someday.

**Comment by eh2iu** [comment]
I have seen a lot of coments that Fps Unlocker makes Obs studio lag, You may have using some Bad Performance graphic Card of the laptop or PC,The Simple solution is to Make The Roblox Window Small, As small as you could, It will Make graphic Card And Roblox run with good performance, If this still didn't work, you must change your graphic card Settings, If you don't have graphic and your lagging means you must change obs settings,
