### ISSUE TITLE
When I Alt Enter Roblox (fullscreen), the FPS unlocker doesn't work.

### ISSUE THREAD

**Issue by Urmombiggay** [axstin/rbxfpsunlocker#90]
So, I turn on fps unlocker, open roblox, and it works on windowed screen. But when I try to alt enter, my FPS caps at 60. I don't know why but that's too stupid like the fps unlocker works in windowed screen but when i want to play in full screen aka alt enter it doesnt work.

**Comment by CelestiusBlitz** [comment]
Use the built-in fullscreen mode (activated with F-11 or pressing the button) for the frame boost to take effect. Make sure you're not on max graphics (as it lowers your FPS in general). Be sure to check your F-1 screen to make sure that it actually _isnt_ working for sure. Hope this helps.

**Comment by EpicShub** [comment]
it still doesnt WORK

**Comment by Lost-Phantomz1** [comment]
> Use the built-in fullscreen mode (activated with F-11 or pressing the button) for the frame boost to take effect. Make sure you're not on max graphics (as it lowers your FPS in general). Be sure to check your F-1 screen to make sure that it actually _isnt_ working for sure. Hope this helps.

didnt work
