### ISSUE TITLE
Variable Scan Error

### ISSUE THREAD

**Issue by ghost** [axstin/rbxfpsunlocker#91]
![Capture](https://user-images.githubusercontent.com/54881956/64242104-8307fb00-cf37-11e9-958d-949666a46caa.PNG)

**Comment by CelestiusBlitz** [comment]
@CustomIDK Reinstall the program. Did you unpack the file correctly?

**Comment by axstin** [comment]
Does this issue still occur?

**Comment by Joyousevengamerboy2** [comment]
Pls can u fix this issue in the next

**Comment by Joyousevengamerboy2** [comment]
Can you please fix this in the next update.

**Comment by codispoip09** [comment]
please fix this is so annoying!!!!
