### ISSUE TITLE
Decreasing Wifi And Little Laggy

### ISSUE THREAD

**Issue by JpYTGaming** [axstin/rbxfpsunlocker#93]
When used in a few min its starts to decrease my wifi until i get disconected i dont know whats wrong with it and please fix asap.

the exe
is a bit laggy the 4.1 is a bit laggy
i prefer 4.0 its not laggy as 4.1.

And Nice fps boost!
:p

**Comment by mxdanger** [comment]
That's your computer causing the problem. Also, this is an fps UNLOCKER it doesn't boost anything. You should close this issue.
