### ISSUE TITLE
Unlocking Roblox Studio

### ISSUE THREAD

**Issue by SpiffySkycoltenDeveloper13** [axstin/rbxfpsunlocker#94]
Does my unlock Roblox Studio give me more fps in roblox

**Comment by CelestiusBlitz** [comment]
@SpiffySkycoltenDeveloper13 The "Unlock ROBLOX Studio" option only effects the studio version of ROBLOX. If you are not a ROBLOX developer who uses ROBLOX Studio, it serves no purpose for you. This is not an issue.
