### ISSUE TITLE
FPS is not getting higher than 60 fps

### ISSUE THREAD

**Issue by captINgregor** [axstin/rbxfpsunlocker#95]
I am sure that my specs are going to make fps higher than 60, but for some reason it isn't
specs are i7 2.20 ghz and 16 ram

**Comment by CelestiusBlitz** [comment]
FPS is linked to your graphics settings. I've noted that even with my powerful machine, I usually get 60-70 on the highest possible setting on ROBLOX. Usually, if you turn your graphics down near 5 or 6, you get around 180-200 FPS. Most FPS on the lowest. Hope this helps.

**Comment by CelestiusBlitz** [comment]
Please close this issue.
