### ISSUE TITLE
Doesnt Minimize

### ISSUE THREAD

**Issue by ItzAlex1** [axstin/rbxfpsunlocker#97]
When it minimizes the fps unlocker does not minize down into the correct place.
![image](https://user-images.githubusercontent.com/56042532/65984572-fdb13100-e477-11e9-96a3-de21fe1edfe0.png)

**Comment by ItzAlex1** [comment]
yes I have tried reinstalling & reopening, but didn't work

**Comment by axstin** [comment]
If it does minimize _somewhere_, you should be able to click and drag the icon to where you want it in the system tray.
